"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

export default function AdmissionsPublicPage(){
  const [submitted,setSubmitted]=useState(false);
  const [section,setSection]=useState("Primary");
  function submit(e:FormEvent){e.preventDefault();setSubmitted(true)}
  return <main className="admission-public">
    <header className="admission-public-nav"><div className="admission-public-brand"><span>BGA</span><div><strong>BrightGate Academy</strong><small>Knowledge · Character · Excellence</small></div></div><nav><a href="#about">About</a><a href="#admissions">Admissions</a><a href="#life">School Life</a><a href="#contact">Contact</a><Link href="/parent">Parent Portal</Link></nav></header>

    <section className="admission-hero"><div><span>2026/2027 ADMISSIONS NOW OPEN</span><h1>A strong beginning.<br/>A confident future.</h1><p>Nursery, Primary and Secondary education in a caring, structured learning environment.</p><div className="admission-hero-actions"><a href="#apply">Apply for admission</a><a className="secondary" href="#admissions">How admission works</a></div><div className="admission-proof"><div><strong>Nursery</strong><small>Play, care & foundations</small></div><div><strong>Primary</strong><small>Strong literacy & numeracy</small></div><div><strong>Secondary</strong><small>Academic growth & preparation</small></div></div></div><aside><div className="admission-hero-card"><span>ADMISSION JOURNEY</span><strong>Simple online application</strong><ol><li>Apply online</li><li>Upload documents</li><li>Screening / review</li><li>Receive admission decision</li><li>Complete registration</li></ol></div></aside></section>

    <section id="admissions" className="admission-section"><div className="admission-section-head"><span>ADMISSIONS</span><h2>From enquiry to enrollment</h2><p>Parents can complete the admission journey online without visiting the school repeatedly.</p></div><div className="admission-steps">{[["01","Application","Create an application for Nursery, Primary or Secondary."],["02","Documents","Submit required admission documents for review."],["03","Screening","Attend any required entrance assessment or interview."],["04","Offer","Receive the school’s admission decision."],["05","Registration","Complete guardian details, fees setup and enrollment."]].map(x=><article key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><p>{x[2]}</p></article>)}</div></section>

    <section id="apply" className="admission-apply"><div><span>ONLINE APPLICATION</span><h2>Apply to BrightGate Academy</h2><p>This prototype form represents the public school website. Applicants should experience BrightGate Academy branding—not the underlying SchoolOS platform.</p></div>{submitted?<div className="admission-success"><span>✓</span><h3>Application received</h3><p>Application reference <strong>BGA-ADM-26094</strong> has been created.</p><small>The school admissions office will review the application and contact the guardian through the details provided.</small><button onClick={()=>setSubmitted(false)}>Start another application</button></div>:<form onSubmit={submit} className="admission-form"><label>Child full name<input required placeholder="e.g. Aisha Sani"/></label><label>Applying for<select value={section} onChange={e=>setSection(e.target.value)}><option>Nursery</option><option>Primary</option><option>Secondary</option></select></label><label>Proposed class<select><option>Nursery 1</option><option>Nursery 2</option><option>Primary 1</option><option>Primary 2</option><option>Primary 3</option><option>JSS 1</option><option>JSS 2</option><option>SS 1</option></select></label><label>Date of birth<input type="date"/></label><label>Guardian name<input required placeholder="e.g. Alhaji Sani Ibrahim"/></label><label>Guardian phone<input required placeholder="080..."/></label><label>Guardian email<input type="email" placeholder="guardian@example.com"/></label><label>Previous school<input placeholder="Optional"/></label><label className="wide">Home address<textarea rows={3} placeholder="Home address"/></label><div className="wide admission-upload"><strong>Required documents</strong><span>Birth certificate · previous school report · guardian ID</span><button type="button">Choose files</button></div><button className="wide admission-submit" type="submit">Submit application →</button></form>}</section>

    <section id="life" className="admission-section alt"><div className="admission-section-head"><span>SCHOOL EXPERIENCE</span><h2>More than classroom instruction</h2></div><div className="admission-life-grid"><article><strong>Academic tracking</strong><p>Continuous visibility into learning progress across the child’s school journey.</p></article><article><strong>Parent connection</strong><p>Families stay informed about school progress, payments, notices and weekly learning.</p></article><article><strong>Safe operations</strong><p>Attendance, records and school activities are managed through connected workflows.</p></article></div></section>

    <footer id="contact" className="admission-footer"><div><strong>BrightGate Academy</strong><span>12 Learning Avenue, Kaduna, Kaduna State, Nigeria</span></div><div><span>Admissions Office</span><strong>admissions@brightgate.example</strong></div><div><span>Website</span><strong>brightgateacademy.ng</strong></div></footer>
  </main>
}
