import Link from "next/link";

const queue=[
 ["New admission form awaiting document review","ADM-26041 · Aisha Sani · Primary 2","Registration"],
 ["Guardian link needs verification","FAM-BGA-0081 · Umar Faruq","Family account"],
 ["Transfer-out request awaiting records pack","STU-003 · Yusuf Bello","Lifecycle"],
 ["Two attendance correction requests","Secondary · Sep 12","Attendance"],
 ["Staff file missing qualification document","STAFF-021 · Mr. Ahmad Sani","Staff records"],
];

export default function AdministratorDashboard(){return <main>
<header className="admin-head"><div><span className="admin-kicker">SCHOOL ADMINISTRATION · KADUNA CAMPUS</span><h1>Administrator Dashboard</h1><p>Manage student registration, school records, family accounts, staff files and operational workflows.</p></div><div className="admin-actions"><Link href="/administrator/students">Search records</Link><Link className="primary" href="/administrator/registration">＋ Register student</Link></div></header>
<section className="admin-kpis"><article><span>Active students</span><strong>648</strong><small>Across Early Years, Primary and Secondary</small></article><article><span>Admissions in progress</span><strong>17</strong><small>5 awaiting documents</small></article><article><span>Records tasks</span><strong>12</strong><small>Needs admin follow-up</small></article><article><span>Transfers / withdrawals</span><strong>4</strong><small>Current term requests</small></article><article><span>Staff files</span><strong>64</strong><small>3 incomplete records</small></article></section>
<section className="admin-grid two"><article className="admin-card"><header><div><h2>Administration Work Queue</h2><p>Operational records that need action today.</p></div></header><div className="admin-list">{queue.map(([title,detail,area])=><div key={title}><strong>{title}</strong><span>{detail}</span><small>{area}</small></div>)}</div></article><article className="admin-card"><header><div><h2>Today at the Admin Desk</h2><p>Current prototype activity.</p></div></header><div className="admin-list"><div><strong>6 new applications received</strong><span>3 Primary · 2 Secondary · 1 Early Years</span></div><div><strong>4 student IDs prepared</strong><span>Admission numbers and ID previews generated</span></div><div><strong>9 documents verified</strong><span>Birth certificates, previous-school records and guardian IDs</span></div><div><strong>3 family accounts updated</strong><span>Guardian-child relationships confirmed</span></div></div></article></section>
<section className="admin-quick"><Link href="/administrator/registration"><strong>Student Registration</strong><span>Create admission record, guardian links, admission number and class placement.</span></Link><Link href="/administrator/students"><strong>Students & Families</strong><span>Search and maintain student and guardian records.</span></Link><Link href="/administrator/lifecycle"><strong>Transfers & Promotion</strong><span>Process transfers, withdrawals, promotion and alumni transitions.</span></Link><Link href="/administrator/records"><strong>Records & Documents</strong><span>Verify, store and track official school documents.</span></Link><Link href="/finance-office/scholarships"><strong>Request Scholarship / Discount</strong><span>Submit a concession for a student. Only the Proprietor can approve it.</span></Link></section>
<section className="admin-card" style={{marginTop:14}}><div className="admin-callout"><strong>Administrator authority:</strong> the role can create and maintain operational records and request scholarships or discounts, but cannot finalize academic results, override section leadership, expose confidential payroll, approve safeguarding outcomes, approve a scholarship or discount, or make other proprietor governance decisions.</div></section>
</main>}
