"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import styles from "./student-intelligence.module.css";

type RoleMode="principal"|"headmaster"|"parent";
type Student={id:string;name:string;className:string;section:string;average:number;attendance:number;trend:number;status:"Strong"|"Stable"|"Watch"|"Needs support";history:number[];subjects:{name:string;exam:number;classwork:number;assignment:number;trend:string}[];topics:{name:string;score:number;note:string}[];evidence:{label:string;value:string;note:string}[];timeline:{title:string;detail:string;date:string}[];insight:string;actions:string[]};

const students:Student[]=[
 {id:"STU-001",name:"Maryam Abdullahi",className:"JSS 2A",section:"Secondary",average:86,attendance:96,trend:4.2,status:"Strong",history:[72,76,74,81,79,84,86],subjects:[{name:"Mathematics",exam:88,classwork:84,assignment:91,trend:"+3.0"},{name:"English",exam:84,classwork:86,assignment:88,trend:"+2.1"},{name:"Basic Science",exam:87,classwork:82,assignment:89,trend:"+5.2"},{name:"Social Studies",exam:85,classwork:83,assignment:86,trend:"+4.0"}],topics:[{name:"Fractions",score:62,note:"Needs another guided practice cycle"},{name:"Algebra",score:91,note:"Current strength"},{name:"Geometry",score:69,note:"Improving but inconsistent"},{name:"Comprehension",score:87,note:"Strong recent evidence"}],evidence:[{label:"Exams",value:"86%",note:"Current term average"},{label:"Classwork",value:"84%",note:"14 activities"},{label:"Assignments",value:"89%",note:"92% completion"},{label:"Attendance",value:"96%",note:"2 late arrivals"}],timeline:[{date:"12 Sep",title:"Mathematics topic review",detail:"Fractions remained below Maryam's other Mathematics topics."},{date:"8 Sep",title:"Basic Science improvement",detail:"Assessment evidence rose after guided revision."},{date:"2 Sep",title:"Assignment consistency",detail:"All scheduled assignments submitted this week."}],insight:"Maryam's overall learning trend is improving. Algebra and comprehension are current strengths; fractions still need reinforcement before more difficult ratio work.",actions:["Give one additional fractions practice set","Check geometry again after two more class activities","Continue normal enrichment in English and Basic Science"]},
 {id:"STU-003",name:"Yusuf Bello",className:"JSS 2B",section:"Secondary",average:48,attendance:79,trend:-8.4,status:"Watch",history:[66,64,61,58,55,51,48],subjects:[{name:"Mathematics",exam:42,classwork:47,assignment:50,trend:"-11.0"},{name:"English",exam:51,classwork:55,assignment:58,trend:"-5.0"},{name:"Basic Science",exam:46,classwork:49,assignment:45,trend:"-9.0"},{name:"Social Studies",exam:53,classwork:57,assignment:60,trend:"-4.0"}],topics:[{name:"Fractions",score:39,note:"Repeated difficulty across three evidence types"},{name:"Algebra",score:44,note:"Needs guided review"},{name:"Reading comprehension",score:56,note:"More stable than Mathematics"},{name:"Energy",score:41,note:"Recent Science weakness"}],evidence:[{label:"Exams",value:"48%",note:"Current term average"},{label:"Classwork",value:"52%",note:"11 activities"},{label:"Assignments",value:"54%",note:"76% completion"},{label:"Attendance",value:"79%",note:"6 unexplained absences"}],timeline:[{date:"12 Sep",title:"Coordinated follow-up",detail:"Academic decline and attendance weakness reviewed together."},{date:"8 Sep",title:"Mathematics revision started",detail:"Short guided support plan opened by teacher."},{date:"4 Sep",title:"Attendance pattern reviewed",detail:"Repeated absences flagged for human follow-up without inferring a family cause."}],insight:"Yusuf's recent decline appears across multiple subjects and is occurring alongside lower attendance. The next step should combine learning support with attendance follow-up rather than treating either signal alone.",actions:["Review Mathematics foundations in a short intervention cycle","Coordinate guardian conversation about recent attendance facts","Recheck progress after two weeks before changing the support plan"]},
 {id:"PRI-003",name:"Hafsa Abdullahi",className:"Primary 3",section:"Primary",average:58,attendance:82,trend:-6.8,status:"Needs support",history:[69,68,66,64,62,60,58],subjects:[{name:"Literacy",exam:54,classwork:58,assignment:61,trend:"-8.0"},{name:"Numeracy",exam:61,classwork:63,assignment:66,trend:"-3.0"},{name:"Basic Science",exam:60,classwork:62,assignment:64,trend:"-4.0"},{name:"Creative Arts",exam:78,classwork:82,assignment:80,trend:"+2.0"}],topics:[{name:"Reading fluency",score:52,note:"Needs guided reading practice"},{name:"Spelling patterns",score:57,note:"Still inconsistent"},{name:"Number bonds",score:68,note:"More secure"},{name:"Creative expression",score:82,note:"Current strength"}],evidence:[{label:"Assessments",value:"58%",note:"Current term evidence"},{label:"Classwork",value:"63%",note:"16 activities"},{label:"Assignments",value:"66%",note:"88% completion"},{label:"Attendance",value:"82%",note:"4 late arrivals"}],timeline:[{date:"11 Sep",title:"Reading support review",detail:"Teacher recommended continued guided reading practice."},{date:"7 Sep",title:"Attendance follow-up",detail:"Headmistress requested a guardian conversation about the attendance pattern."},{date:"3 Sep",title:"Creative activity",detail:"Strong participation recorded during creative work."}],insight:"Hafsa shows stronger evidence in creative work and numeracy than in reading fluency. Reading support should continue, while attendance context should be monitored over the next learning cycle.",actions:["Continue guided reading in short sessions","Use spelling practice tied to current class texts","Review progress after the next two literacy activities"]}
];

export default function StudentIntelligenceView({mode}:{mode:RoleMode}){
 const allowed=useMemo(()=>mode==="parent"?students.filter(s=>s.id==="STU-001"||s.id==="PRI-003"):mode==="headmaster"?students.filter(s=>s.section==="Primary"):students.filter(s=>s.section==="Secondary"),[mode]);
 const [selectedId,setSelectedId]=useState(allowed[0]?.id??students[0].id);const student=allowed.find(s=>s.id===selectedId)??allowed[0]??students[0];
 const back=mode==="principal"?"/principal/students":mode==="headmaster"?"/headmaster/pupils":"/parent/children";
 const title=mode==="parent"?"Learning Progress":"Student 360 Intelligence";
 const kicker=mode==="principal"?"PRINCIPAL · STUDENT INTELLIGENCE":mode==="headmaster"?"PRIMARY · PUPIL INTELLIGENCE":"FAMILY PORTAL · LEARNING PROGRESS";
 return <main className={styles.siPage}>
  <header className={styles.siHead}><div><span>{kicker}</span><h1>{title}</h1><p>{mode==="parent"?"See how your child is progressing across exams, classwork, assignments and attendance, with clear areas to practise next.":"Review historical performance, topic-level evidence, ongoing classwork and supportive next actions without reducing a child to one score."}</p></div><Link href={back}>Back</Link></header>
  <section className={styles.kpis}><article><span>Current average</span><strong>{student.average}%</strong><small>{student.trend>0?"Improving":"Needs review"} · {student.trend>0?"+":""}{student.trend}% trend</small></article><article><span>Attendance</span><strong>{student.attendance}%</strong><small>Context, not a cause by itself</small></article><article><span>Assignment completion</span><strong>{student.evidence[2].value}</strong><small>{student.evidence[2].note}</small></article><article><span>Strongest topic</span><strong>{[...student.topics].sort((a,b)=>b.score-a.score)[0].score}%</strong><small>{[...student.topics].sort((a,b)=>b.score-a.score)[0].name}</small></article><article><span>Priority topic</span><strong>{[...student.topics].sort((a,b)=>a.score-b.score)[0].score}%</strong><small>{[...student.topics].sort((a,b)=>a.score-b.score)[0].name}</small></article></section>
  <section className={styles.grid}><article className={styles.card}><header><div><h2>{mode==="parent"?"My children":"Student directory"}</h2><p>Select a child to review the complete learning picture.</p></div></header><div className={styles.studentList}>{allowed.map(s=><button key={s.id} onClick={()=>setSelectedId(s.id)} className={s.id===student.id?styles.active:""}><div><strong>{s.name}</strong><span>{s.className} · {s.section}</span><small>Avg {s.average}% · Attendance {s.attendance}%</small></div><b>{s.trend>0?"+":""}{s.trend}%</b><em className={`${styles.pill} ${s.status==="Watch"?styles.watch:s.status==="Needs support"?styles.support:""}`}>{s.status}</em></button>)}</div></article><article className={styles.card}><header><div><h2>Historical performance</h2><p>Seven-term learning trend.</p></div></header><div className={styles.history}>{student.history.map((v,i)=><div key={i}><i style={{height:`${Math.max(20,v)}%`}}/><b>{v}%</b><span>T{i+1}</span></div>)}</div></article></section>
  <section className={styles.card} style={{marginBottom:14}}><header><div><h2>Subject evidence</h2><p>Exams are only one part of the picture; classwork and assignments are shown beside them.</p></div></header><div className={styles.subjectTable}><div className={styles.subjectHead}><span>Subject</span><span>Exam</span><span>Classwork</span><span>Assignment</span><span>Trend</span></div>{student.subjects.map(s=><div className={styles.subjectRow} key={s.name}><strong>{s.name}</strong><span>{s.exam}%</span><span>{s.classwork}%</span><span>{s.assignment}%</span><b>{s.trend}</b></div>)}</div></section>
  <section className={styles.grid}><article className={styles.card}><header><div><h2>Topic-level learning map</h2><p>Pinpoint what needs reinforcement instead of labelling the whole subject as weak.</p></div></header><div className={styles.topicGrid}>{student.topics.map(t=><div className={styles.topic} key={t.name}><strong>{t.name}</strong><span>{t.score}% evidence</span><div className={styles.meter}><i style={{width:`${t.score}%`}}/></div><small>{t.note}</small></div>)}</div></article><article className={styles.card}><header><div><h2>Evidence mix</h2><p>Current learning signals used in this prototype view.</p></div></header><div className={styles.evidence}>{student.evidence.map(e=><div key={e.label}><span>{e.label}</span><strong>{e.value}</strong><small>{e.note}</small></div>)}</div></article></section>
  <section className={styles.grid}><article className={styles.insight}><h2>{mode==="parent"?"Learning insight":"AI-supported learning insight"}</h2><p>{student.insight}</p><ul>{student.actions.map(a=><li key={a}>{a}</li>)}</ul></article><article className={styles.card}><header><div><h2>Recent learning timeline</h2><p>Interventions, assessments and review points.</p></div></header><div className={styles.timeline}>{student.timeline.map(t=><div key={`${t.date}-${t.title}`}><strong>{t.title}</strong><span>{t.detail}</span><small>{t.date}</small></div>)}</div></article></section>
  <div className={styles.guardianNote}>{mode==="parent"?"This view explains current learning evidence and suggested practice areas. It is not a permanent ability label, diagnosis or class ranking.":"Student Intelligence is for support planning. AI may summarize patterns and suggest next checks, but teachers and academic leaders remain responsible for interpretation and intervention decisions."}</div>
 </main>
}
