"use client";

import { useMemo, useState } from "react";
import SchoolLifeNav from "../../components/school-life-nav";
import "../school-life.css";

type TripStatus = "Planning" | "Consent open" | "Ready" | "Completed";
type Trip = { id:string; title:string; audience:string; date:string; destination:string; coordinator:string; students:number; consentReceived:number; transport:string; emergency:string; status:TripStatus; note:string };

const seed:Trip[]=[
  {id:"TRIP-001",title:"Science Discovery Trip",audience:"JSS 2",date:"26 Sep 2026",destination:"Kaduna Science Centre",coordinator:"Science Department",students:86,consentReceived:68,transport:"2 school buses",emergency:"Manifest + emergency contacts pending final review",status:"Consent open",note:"Science learning visit with supervised groups and guardian approval."},
  {id:"TRIP-002",title:"Primary 6 Museum Visit",audience:"Primary 6",date:"3 Oct 2026",destination:"Kaduna Museum",coordinator:"Primary School",students:34,consentReceived:34,transport:"1 school bus",emergency:"Complete",status:"Ready",note:"History and cultural-learning visit with class-teacher supervision."},
  {id:"TRIP-003",title:"Early Years Nature Walk",audience:"Reception A",date:"8 Oct 2026",destination:"School botanical garden",coordinator:"Mrs. Mary Daniel",students:26,consentReceived:21,transport:"On-campus walking route",emergency:"Group contact list ready",status:"Consent open",note:"Short age-appropriate supervised nature activity within the school environment."},
  {id:"TRIP-004",title:"Robotics Inter-School Showcase",audience:"Coding & Robotics Club",date:"15 Oct 2026",destination:"Innovation Hub",coordinator:"Mr. Samuel Ter",students:18,consentReceived:18,transport:"School minibus",emergency:"Complete",status:"Ready",note:"Club representation at an inter-school technology showcase."},
];

export default function ExcursionsPage(){
  const [status,setStatus]=useState("All statuses");
  const [query,setQuery]=useState("");
  const [reviewed,setReviewed]=useState<string[]>([]);
  const visible=useMemo(()=>seed.filter(t=>(status==="All statuses"||t.status===status)&&`${t.title} ${t.audience} ${t.destination}`.toLowerCase().includes(query.toLowerCase())),[status,query]);
  const openConsent=seed.reduce((sum,t)=>sum+(t.students-t.consentReceived),0);
  return <main className="school-life-page">
    <SchoolLifeNav active="excursions" />
    <section className="school-life-scope"><div><strong>Excursions & Consent</strong><span>Trips, transport and guardian approval</span></div><p>Plan off-site and supervised special activities with audience, transport, consent, emergency-contact and readiness visibility.</p></section>
    <section className="school-life-stat-grid"><article className="school-life-stat"><span>Planned trips</span><strong>{seed.length}</strong><small>Representative current term</small></article><article className="school-life-stat"><span>Consent outstanding</span><strong>{openConsent}</strong><small>Across current mock trips</small></article><article className="school-life-stat"><span>Ready to go</span><strong>{seed.filter(t=>t.status==="Ready").length}</strong><small>Consent + readiness complete</small></article><article className="school-life-stat"><span>Transport plans</span><strong>4</strong><small>Linked per trip</small></article><article className="school-life-stat"><span>Unreviewed readiness</span><strong>{seed.length-reviewed.length}</strong><small>Local UI review state</small></article></section>
    <section className="school-life-grid"><article className="school-life-card"><div className="school-life-section-head"><div><h2>Trip register</h2><p>Readiness should be complete before departure, not reconstructed afterward.</p></div></div><div className="school-life-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search trip, destination or audience..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option><option>Planning</option><option>Consent open</option><option>Ready</option><option>Completed</option></select></div><div className="activity-list">{visible.map(t=>{const pct=Math.round((t.consentReceived/t.students)*100);const done=reviewed.includes(t.id);return <div className="activity-row" key={t.id}><div className="activity-icon">↗</div><div><div className="activity-meta"><span>{t.status}</span><span>{t.audience}</span><span>{pct}% consent</span></div><h3>{t.title}</h3><p>{t.date} · {t.destination} · {t.coordinator}</p><p>{t.note}</p><div className="activity-progress"><i style={{width:`${pct}%`}}/></div><small>{t.consentReceived}/{t.students} consent received · {t.transport} · {t.emergency}</small><div className="notice-actions" style={{marginTop:8}}><button onClick={()=>setReviewed(c=>c.includes(t.id)?c.filter(id=>id!==t.id):[...c,t.id])}>{done?"Reopen review":"Mark readiness reviewed"}</button></div></div><span className="activity-status">{done?"Reviewed":t.status}</span></div>})}</div></article><aside className="school-life-sidebar"><article className="school-life-card"><span className="school-life-kicker">DEPARTURE CHECK</span><div className="school-life-policy-list"><div><strong>Guardian consent</strong><small>Required where school policy says so.</small></div><div><strong>Transport manifest</strong><small>Vehicle, adults and participant list.</small></div><div><strong>Emergency contacts</strong><small>Accessible to authorized supervising staff.</small></div><div><strong>Medical/access needs</strong><small>Handled privately and only where necessary for safe participation.</small></div></div></article><article className="school-life-card"><span className="school-life-kicker">PRIVACY RULE</span><p style={{margin:"6px 0 0",color:"#69768a",fontSize:12,lineHeight:1.65}}>The general trip view should not expose sensitive medical or family information. Supervisors receive only the minimum necessary safety information through restricted workflows later.</p></article></aside></section>
  </main>;
}
