"use client";

import { useMemo, useState } from "react";

const questions=[
 {topic:"Linear Equations",text:"If 3x + 4 = 19, what is the value of x?",options:["3","4","5","6"],answer:2},
 {topic:"Fractions",text:"What is 3/4 + 1/8?",options:["4/12","7/8","5/8","1"],answer:1},
 {topic:"Geometry",text:"A triangle has angles 50° and 60°. What is the third angle?",options:["60°","70°","80°","90°"],answer:1},
 {topic:"Word Problems",text:"Amina has 5 packs of 6 pencils. How many pencils does she have?",options:["11","25","30","36"],answer:2},
 {topic:"Linear Equations",text:"Solve x - 7 = 12.",options:["5","17","19","21"],answer:2},
];

export default function CbtKioskPage(){
 const [phase,setPhase]=useState<"entry"|"exam"|"result">("entry");const [studentId,setStudentId]=useState("BGA/2023/SEC/001");const [pin,setPin]=useState("482931");const [current,setCurrent]=useState(0);const [answers,setAnswers]=useState<Record<number,number>>({});
 const score=useMemo(()=>questions.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),[answers]);
 const q=questions[current];
 const topicStats=useMemo(()=>{const stats:Record<string,{right:number,total:number}>={};questions.forEach((item,i)=>{stats[item.topic]??={right:0,total:0};stats[item.topic].total++;if(answers[i]===item.answer)stats[item.topic].right++});return Object.entries(stats)},[answers]);
 if(phase==="entry")return <main className="cbt-kiosk"><header className="cbt-kiosk-head"><div className="cbt-kiosk-brand"><i>B</i><div><strong>BrightGate Academy</strong><span>CBT Practice Center</span></div></div><small>Practice environment</small></header><div className="cbt-entry"><section><span className="page-kicker">COMPUTER-BASED PRACTICE</span><h1>Learn the CBT exam experience before exam day.</h1><p>This practice helps students become familiar with question navigation, timing, answering, reviewing and submitting a computer-based test.</p><div className="cbt-entry-form"><label>Student / admission number<input value={studentId} onChange={e=>setStudentId(e.target.value)}/></label><label>Practice PIN<input value={pin} onChange={e=>setPin(e.target.value)}/></label><label>Practice set<select defaultValue="math"><option value="math">JSS 2 Mathematics · Linear Equations</option><option>JSS 2 Mathematics · Fractions Review</option></select></label><button className="cbt-primary" onClick={()=>setPhase("exam")}>Start practice</button></div></section><aside><h2>Before you start</h2><div className="admin-list"><div><strong>20 questions</strong><span>Prototype set shortened to 5 questions in this UI demo.</span></div><div><strong>20 minutes</strong><span>A timer remains visible throughout the practice.</span></div><div><strong>Move between questions</strong><span>You can return to previous questions before final submission.</span></div><div><strong>Learning feedback</strong><span>After practice, see overall accuracy and topics to practise again.</span></div></div></aside></div></main>;
 if(phase==="result")return <main className="cbt-kiosk"><header className="cbt-kiosk-head"><div className="cbt-kiosk-brand"><i>B</i><div><strong>BrightGate Academy</strong><span>CBT Practice Center</span></div></div><small>Practice completed</small></header><div className="cbt-result"><section className="cbt-result-card"><span className="page-kicker">PRACTICE RESULT</span><h1>Practice completed</h1><p>Maryam Abdullahi · JSS 2A · Mathematics</p><div className="cbt-result-score"><div><span>Score</span><strong>{score}/{questions.length}</strong></div><div><span>Accuracy</span><strong>{Math.round(score/questions.length*100)}%</strong></div><div><span>Answered</span><strong>{Object.keys(answers).length}</strong></div><div><span>Time used</span><strong>14m</strong></div></div><h2>Topic feedback</h2><div className="cbt-topic-grid">{topicStats.map(([topic,s])=><div key={topic}><span>{topic}</span><strong>{s.right}/{s.total} correct</strong></div>)}</div><div className="cbt-insight" style={{marginTop:14}}><strong>Practice suggestion</strong><span>Review the topics with missed questions, then try another short practice. This score is learning evidence and is not a permanent label or class ranking.</span></div><button className="cbt-primary" style={{marginTop:14}} onClick={()=>{setPhase("entry");setCurrent(0);setAnswers({})}}>Return to practice entry</button></section></div></main>;
 return <main className="cbt-kiosk"><header className="cbt-kiosk-head"><div className="cbt-kiosk-brand"><i>B</i><div><strong>BrightGate Academy</strong><span>JSS 2 Mathematics Practice</span></div></div><div><strong>Maryam Abdullahi</strong><small>JSS 2A</small></div></header><div className="cbt-exam-wrap"><section className="cbt-exam-main"><span className="page-kicker">QUESTION {current+1} OF {questions.length} · {q.topic}</span><h2>Mathematics CBT Practice</h2><div className="cbt-question-text">{q.text}</div><div className="cbt-answer-list">{q.options.map((o,i)=><button key={o} className={answers[current]===i?"selected":""} onClick={()=>setAnswers(a=>({...a,[current]:i}))}><strong>{String.fromCharCode(65+i)}.</strong> {o}</button>)}</div><div className="cbt-exam-actions"><button disabled={current===0} onClick={()=>setCurrent(v=>Math.max(0,v-1))}>← Previous</button>{current<questions.length-1?<button onClick={()=>setCurrent(v=>Math.min(questions.length-1,v+1))}>Next →</button>:<button className="cbt-primary" onClick={()=>setPhase("result")}>Submit practice</button>}</div></section><aside className="cbt-exam-side"><h3>Time remaining</h3><div className="cbt-timer">14:32</div><p>{Object.keys(answers).length} of {questions.length} answered</p><h3>Questions</h3><div className="cbt-qnav">{questions.map((_,i)=><button key={i} className={`${current===i?"current":""} ${answers[i]!==undefined?"answered":""}`} onClick={()=>setCurrent(i)}>{i+1}</button>)}</div><div className="cbt-insight" style={{marginTop:14}}><strong>Practice tip</strong><span>You may move between questions before submitting. Review unanswered questions before finishing.</span></div></aside></div></main>;
}
