"use client";
import Link from "next/link";
import { useState } from "react";

const prompts=["Why is Secondary attendance below target?","Compare fee collection by section","Which owner priorities need action this week?","Summarize enrollment and retention risk","What changed in staffing this term?"];

export default function ProprietorAIPage(){const [query,setQuery]=useState("");const [asked,setAsked]=useState("Which owner priorities need action this week?");return <main className="owner-module-page">
<header className="owner-module-head"><div><span>PROPRIETOR · SCHOOL AI</span><h1>Proprietor AI</h1><p>Ask whole-school management questions using owner-authorized context while preserving campus, section and sensitive-data boundaries.</p></div><div className="owner-module-actions"><Link href="/proprietor">Executive Overview</Link><button className="primary">New executive brief</button></div></header>
<OwnerNav active="ai"/>
<section className="owner-module-ai"><span>AI</span><div><h2>Owner Intelligence Assistant</h2><p>Designed for questions about finance, enrollment, staffing, performance and operations. It should explain the evidence behind an answer and distinguish known facts from interpretation.</p><div>{prompts.slice(0,3).map(p=><button key={p} onClick={()=>setAsked(p)}>{p}</button>)}</div></div></section>
<section className="owner-module-grid two" style={{marginTop:14}}><article className="owner-module-card"><header><div><h2>Ask Your School</h2><p>Prototype conversation using mock proprietor-authorized data.</p></div></header><div className="owner-module-chat"><div className="user"><strong>YOU</strong><p>{asked}</p></div><div className="ai"><strong>SCHOOLOS AI</strong><p>The current owner attention queue has four items: Secondary attendance at 90% versus a 94% target, ₦3.7m outstanding fees across 73 family accounts, two Secondary curriculum pacing gaps, and one unfilled Primary 6 class-teacher responsibility. The strongest owner action is to assign follow-up owners and review context; this mock UI does not infer family causes or make automatic employment decisions.</p></div></div><div className="owner-module-prompt"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask a whole-school question..."/><button onClick={()=>{if(query.trim()){setAsked(query.trim());setQuery("")}}}>Ask AI</button></div></article><article className="owner-module-card"><header><div><h2>Suggested questions</h2><p>Management questions suited to proprietor scope.</p></div></header><div className="owner-module-list">{prompts.map(p=><div key={p} onClick={()=>setAsked(p)} style={{cursor:"pointer"}}><strong>{p}</strong><span>Uses aggregate, role-authorized school context.</span></div>)}</div></article></section>
<section className="owner-module-grid equal"><article className="owner-module-card"><header><div><h2>AI context boundary</h2><p>Hard production principle.</p></div></header><div className="owner-module-callout">Before the model receives context, SchoolOS should filter by tenant, campus, section, role and record sensitivity. The AI should never receive data merely because the user can type a question about it.</div></article><article className="owner-module-card"><header><div><h2>Decision boundary</h2><p>AI advises; authorized humans decide.</p></div></header><div className="owner-module-callout warn">Proprietor AI must not autonomously fire staff, approve or deny loans, diagnose children, rank families, decide safeguarding outcomes, or take financial action. It can summarize evidence, identify inconsistencies and suggest questions for human review.</div></article></section>
</main>}
function OwnerNav({active}:{active:string}){const links=[["finance","Finance","/proprietor/finance"],["enrollment","Enrollment","/proprietor/enrollment"],["staff","Staff & HR","/proprietor/staff"],["reports","Reports","/proprietor/reports"],["campuses","Campuses","/proprietor/campuses"],["ai","Proprietor AI","/proprietor/ai"]];return <nav className="owner-module-nav">{links.map(([k,l,h])=><Link key={k} className={active===k?"active":""} href={h}>{l}</Link>)}</nav>}