import Link from "next/link";

const payments=[
 ["PAY-260913-204","Maryam Abdullahi","Term account transfer","₦50,000","Matched"],
 ["PAY-260913-198","Hafsa Abdullahi","Parent monthly debit","₦25,000","Matched"],
 ["PAY-260913-191","Unmatched transfer","Bank transfer","₦80,000","Review"],
 ["PAY-260912-177","Yusuf Bello","Term account transfer","₦35,000","Matched"],
];

export default function FinanceOfficePage(){return <main>
<header className="fo-head"><div><span>FINANCE OFFICE · DAILY CONTROL</span><h1>Finance Dashboard</h1><p>Collections, reconciliation, outstanding balances, expenses, financing and reporting in one workspace.</p></div><div className="fo-actions"><Link href="/finance">Open Finance Center</Link><Link className="primary" href="/finance-office/reconciliation">Reconcile payments</Link></div></header>
<section className="fo-kpis"><article><span>Term billed</span><strong>₦62.8m</strong><small>All active student accounts</small></article><article><span>Collected</span><strong>₦59.1m</strong><small>94.1% collection</small></article><article><span>Outstanding</span><strong>₦3.7m</strong><small>73 family accounts</small></article><article><span>Unmatched receipts</span><strong>7</strong><small>₦386,000 awaiting review</small></article><article><span>Cash & bank position</span><strong>₦21.4m</strong><small>Mock operational balance</small></article></section>
<section className="fo-grid two"><article className="fo-card"><header><div><h2>Recent collection activity</h2><p>Latest student-account and bank reconciliation events.</p></div><Link href="/finance-office/reconciliation">Open reconciliation</Link></header><div className="fo-table"><div className="fo-table-head"><span>Reference</span><span>Student/account</span><span>Channel</span><span>Amount</span><span>Status</span></div>{payments.map(r=><div className="fo-table-row" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span><b>{r[3]}</b><em>{r[4]}</em></div>)}</div></article><aside className="fo-card"><header><div><h2>Finance attention queue</h2><p>Items requiring human review.</p></div></header><div className="fo-list"><div><strong>7 unmatched receipts</strong><span>Verify sender/reference before allocation.</span><small>Bank reconciliation</small></div><div><strong>3 reversal requests</strong><span>Require supporting evidence and approval trail.</span><small>Payments</small></div><div><strong>₦150k financing outstanding</strong><span>Two active education-financing facilities.</span><small>No automated eligibility decision</small></div><div><strong>August payroll package ready</strong><span>HR-approved figures awaiting finance payment confirmation.</span><small>Payroll handoff</small></div></div></aside></section>
<section className="fo-grid equal"><article className="fo-card"><header><div><h2>Collection trend</h2><p>Current-term cumulative collection rate.</p></div></header><div className="fo-bars">{[72,78,81,84,88,91,94].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><b>{v}%</b><span>W{i+1}</span></div>)}</div></article><article className="fo-card"><header><div><h2>Today’s operational position</h2><p>Quick finance-office summary.</p></div></header><div className="fo-list"><div><strong>₦1.24m received today</strong><span>31 matched payment events.</span></div><div><strong>₦286k expenses posted</strong><span>Utilities, transport fuel and supplies.</span></div><div><strong>118 recurring parent plans</strong><span>Guardian-authorized schedules only.</span></div><div><strong>5 approval items</strong><span>Refunds, reversals and financing actions.</span></div></div></article></section>
</main>}
