"use client";

import { useState } from "react";

const mandates=[
 {id:"MDT-26041",guardian:"Alhaji Abdullahi Yusuf",children:"Maryam + Hafsa",method:"Bank direct debit",provider:"Remita / partner rail",amount:30000,day:"25th monthly",next:"25 Sep 2026",status:"Active",attempt:"Successful"},
 {id:"MDT-26042",guardian:"Alhaji Musa Bello",children:"Yusuf Bello",method:"Salary-linked",provider:"Lendsqr / partner rail",amount:30000,day:"28th monthly",next:"28 Sep 2026",status:"Active",attempt:"Failed"},
 {id:"MDT-26043",guardian:"Hajiya Aisha Aliyu",children:"Zainab Aliyu",method:"Bank direct debit",provider:"Partner Bank B",amount:20000,day:"20th monthly",next:"20 Sep 2026",status:"Pending consent",attempt:"Not started"},
];
const money=(n:number)=>`₦${n.toLocaleString("en-NG")}`;

export default function MandatesPage(){
 const [selected,setSelected]=useState(mandates[0]);
 const [notice,setNotice]=useState("");
 return <main><header className="fo-head"><div><span>REVENUE ASSURANCE · CONSENT-BASED COLLECTION</span><h1>Payment Mandates</h1><p>Track parent-authorized recurring bank or salary-linked school-fee deductions.</p></div><div className="fo-actions"><button>Export mandates</button><button className="primary">＋ Create mandate</button></div></header>
 <section className="fo-kpis"><article><span>Active mandates</span><strong>412</strong><small>School-wide prototype</small></article><article><span>Expected next 30 days</span><strong>₦11.3M</strong><small>Scheduled collections</small></article><article><span>Successful this month</span><strong>286</strong><small>Completed attempts</small></article><article><span>Failed attempts</span><strong>7</strong><small>Need action</small></article><article><span>Pending consent</span><strong>19</strong><small>Not yet active</small></article></section>
 <section className="fo-grid two"><article className="fo-card"><header><div><h2>Mandate register</h2><p>Parent consent, deduction schedule and latest attempt.</p></div></header><div className="mandate-list">{mandates.map(m=><button key={m.id} onClick={()=>{setSelected(m);setNotice("")}} className={selected.id===m.id?"active":""}><div><strong>{m.guardian}</strong><span>{m.children}</span></div><div><b>{money(m.amount)}</b><small>{m.day}</small></div><em className={m.status.includes("Pending")?"pending":""}>{m.status}</em></button>)}</div></article>
 <article className="fo-card mandate-detail"><header><div><h2>{selected.guardian}</h2><p>{selected.id} · {selected.children}</p></div><span className="smart-tag">{selected.status}</span></header><div className="smart-money-grid"><div><span>Authorized amount</span><strong>{money(selected.amount)}</strong></div><div><span>Schedule</span><strong>{selected.day}</strong></div><div><span>Next attempt</span><strong>{selected.next}</strong></div><div><span>Latest result</span><strong>{selected.attempt}</strong></div></div><div className="fo-list"><div><strong>Collection method</strong><span>{selected.method}</span></div><div><strong>Provider rail</strong><span>{selected.provider}</span></div><div><strong>Consent record</strong><span>Parent authorization captured · prototype</span></div></div><div className="mandate-actions"><button onClick={()=>setNotice("Retry queued locally in prototype.")}>Retry collection</button><button onClick={()=>setNotice("Mandate reschedule opened locally.")}>Reschedule</button><button onClick={()=>setNotice("Mandate paused locally in prototype.")}>Pause mandate</button><button onClick={()=>setNotice("Guardian contact workflow opened.")}>Contact guardian</button></div>{notice&&<div className="fo-callout" style={{marginTop:10}}>{notice}</div>}</article></section>
 <section className="fo-card"><header><div><h2>Mandate workflow</h2><p>The UI keeps authorization, collection and school-fee posting separate but connected.</p></div></header><div className="mandate-flow"><div><b>1</b><strong>Parent chooses plan</strong><span>Amount + frequency</span></div><i>→</i><div><b>2</b><strong>Consent captured</strong><span>Mandate reference</span></div><i>→</i><div><b>3</b><strong>Provider attempts debit</strong><span>Bank / salary rail</span></div><i>→</i><div><b>4</b><strong>SchoolOS posts payment</strong><span>Student fee ledger</span></div><i>→</i><div><b>5</b><strong>Receipt issued</strong><span>Parent portal</span></div></div></section></main>
}
