"use client";

import { useState } from "react";

const receipts=[
 {no:"BGA/RCPT/2026/004819",student:"Maryam Abdullahi",className:"JSS 2A",admission:"BGA/2023/SEC/001",amount:25000,date:"13 Sep 2026",method:"Student Term Account",ref:"TRX-260913-94821",previous:150000,newBalance:125000},
 {no:"BGA/RCPT/2026/004790",student:"Hafsa Abdullahi",className:"Primary 3",admission:"BGA/2022/PRI/003",amount:20000,date:"12 Sep 2026",method:"Student Term Account",ref:"TRX-260912-0041",previous:75000,newBalance:55000},
 {no:"BGA/RCPT/2026/004733",student:"Maryam Abdullahi",className:"JSS 2A",admission:"BGA/2023/SEC/001",amount:20000,date:"06 Sep 2026",method:"Student Term Account",ref:"TRX-260906-0033",previous:170000,newBalance:150000},
];
const money=(n:number)=>`₦${n.toLocaleString("en-NG")}`;

export default function ParentReceiptsPage(){const [selected,setSelected]=useState(receipts[0]);return <main className="family-page"><header className="family-head"><div><span className="family-kicker">FAMILY ACCOUNT · RECEIPTS</span><h1>Payment Receipts</h1><p>Confirmed school-fee payments for your linked children.</p></div><div className="family-actions"><a href="/parent/finance">Back to finance</a><button className="primary" onClick={()=>window.print()}>Print receipt</button></div></header><section className="family-grid two"><article className="family-card"><header><div><h2>Receipt history</h2><p>Select any confirmed payment.</p></div></header><div className="family-list">{receipts.map(r=><button key={r.no} onClick={()=>setSelected(r)} style={{textAlign:"left",cursor:"pointer",background:selected.no===r.no?"#f2f8f6":"#fff"}}><strong>{r.student} · {money(r.amount)}</strong><span>{r.date} · {r.method}</span><small>{r.no}</small></button>)}</div></article><article className="family-card printable-parent-receipt"><div style={{display:"flex",justifyContent:"space-between",gap:12,borderBottom:"1px solid #e5ebee",paddingBottom:12}}><div><strong style={{fontSize:14}}>BrightGate Academy</strong><div style={{fontSize:8,color:"#82929c",marginTop:3}}>Kaduna Campus · Knowledge · Character · Excellence</div></div><b style={{fontSize:9}}>PAYMENT RECEIPT</b></div><div className="info-grid" style={{marginTop:12}}><div><span>Receipt No.</span><strong>{selected.no}</strong></div><div><span>Status</span><strong>Confirmed</strong></div><div><span>Student</span><strong>{selected.student}</strong></div><div><span>Admission No.</span><strong>{selected.admission}</strong></div><div><span>Class</span><strong>{selected.className}</strong></div><div><span>Term</span><strong>2026/2027 · Term 1</strong></div><div><span>Amount paid</span><strong>{money(selected.amount)}</strong></div><div><span>Payment method</span><strong>{selected.method}</strong></div><div><span>Transaction ref</span><strong>{selected.ref}</strong></div><div><span>Payment date</span><strong>{selected.date}</strong></div><div><span>Previous balance</span><strong>{money(selected.previous)}</strong></div><div><span>New balance</span><strong>{money(selected.newBalance)}</strong></div></div><div className="family-callout" style={{marginTop:12}}>System-generated SchoolOS prototype receipt. In production, this record will be created only after the integrated bank/payment provider confirms the credit.</div></article></section></main>}
