import Link from "next/link";

const children=[
 {id:"STU-001",name:"Maryam Abdullahi",className:"JSS 2A",section:"Secondary",attendance:96,academic:86,balance:"₦40,000",initials:"MA"},
 {id:"PRI-003",name:"Hafsa Abdullahi",className:"Primary 3",section:"Primary",attendance:82,academic:58,balance:"₦25,000",initials:"HA"},
];

export default function ParentDashboard(){return <main className="family-page">
  <header className="family-head"><div><span className="family-kicker">PARENT / GUARDIAN · FAMILY ACCOUNT</span><h1>Good evening, Alhaji Abdullahi Yusuf</h1><p>Here is what needs your attention across your linked children today.</p></div><div className="family-actions"><Link href="/parent/messages">Message school</Link><Link className="primary" href="/parent/finance">Pay school fees</Link></div></header>

  <section className="family-banner"><div><span>FAMILY SUMMARY · FAM-BGA-0042</span><h2>Two children. One family workspace.</h2><p>Track learning, attendance, school notices, transport, activities, fees and approved family records without switching between separate accounts.</p></div><div><strong>₦65,000</strong><small>Total current-term balance</small></div></section>

  <section className="family-kpis"><article><span>Linked children</span><strong>2</strong><small>Secondary + Primary</small></article><article><span>Present today</span><strong>2/2</strong><small>Both marked present</small></article><article><span>Current balance</span><strong>₦65k</strong><small>Across both children</small></article><article><span>Next scheduled debit</span><strong>₦25k</strong><small>20 Sep · parent-authorized</small></article><article><span>Unread messages</span><strong>2</strong><small>From school staff</small></article></section>

  <section className="family-grid two"><article className="family-card"><header><div><h2>My children</h2><p>Only children linked to this guardian account are visible.</p></div></header><div className="children-grid">{children.map(child=><div className="child-card" key={child.id}><div className="child-top"><span className="child-avatar">{child.initials}</span><div><strong>{child.name}</strong><small>{child.className} · {child.section}</small></div><em className="status-pill">Present today</em></div><div className="child-metrics"><div><span>Attendance</span><strong>{child.attendance}%</strong></div><div><span>{child.section==="Primary"?"Learning":"Average"}</span><strong>{child.academic}%</strong></div><div><span>Fee balance</span><strong>{child.balance}</strong></div></div><div className="child-actions"><Link href={`/parent/children/${child.id}`}>Open profile</Link><Link href={`/parent/children/${child.id}#reports`}>View report</Link><Link href="/parent/messages">Message school</Link></div></div>)}</div></article>

  <article className="family-card"><header><div><h2>What needs attention</h2><p>Supportive family actions, not automated judgments.</p></div></header><div className="family-list"><div><strong>Hafsa’s attendance is 82%</strong><span>Primary 3 has several absences this term. Review the dates and contact the school if context is missing.</span><small>Attendance · Primary</small></div><div><strong>Next monthly payment is scheduled</strong><span>₦25,000 on 20 September from the family payment plan.</span><small>Finance · Parent-authorized</small></div><div><strong>Consent required for excursion</strong><span>Primary educational visit form is awaiting your response.</span><small>Documents & Consent</small></div></div></article></section>

  <section className="family-grid equal"><article className="family-card"><header><div><h2>Family finance snapshot</h2><p>Current-term accounts for your linked children.</p></div><Link href="/parent/finance">Open finance →</Link></header><div className="finance-summary"><div><span>Total billed</span><strong>₦420,000</strong><small>Term 1</small></div><div><span>Paid</span><strong>₦355,000</strong><small>Receipts available</small></div><div><span>Balance</span><strong>₦65,000</strong><small>Across 2 accounts</small></div></div><div className="family-list" style={{marginTop:10}}><div><strong>Maryam Abdullahi · 1047263815</strong><span>Static payment account for 2026/2027 Term 1 · Balance ₦40,000</span></div><div><strong>Hafsa Abdullahi · 1047263821</strong><span>Static payment account for 2026/2027 Term 1 · Balance ₦25,000</span></div></div></article>

  <article className="family-card"><header><div><h2>Recent messages</h2><p>School communication linked to your children.</p></div><Link href="/parent/messages">View all →</Link></header><div className="message-row"><div><strong>Mrs. Khadija Musa · Primary 3</strong><span>Reading-support materials have been shared for Hafsa.</span></div><small>Today</small></div><div className="message-row"><div><strong>School Finance Office</strong><span>Your monthly payment plan remains active for 20 September.</span></div><small>Yesterday</small></div><div className="message-row"><div><strong>Mrs. Amina Yusuf · JSS 2A</strong><span>Maryam completed the Mathematics assessment.</span></div><small>11 Sep</small></div></article></section>

  <section className="family-grid equal"><article className="family-card"><header><div><h2>Notices & upcoming school life</h2><p>Official notices relevant to this family.</p></div><Link href="/parent/school-life">School Life →</Link></header><div className="notice-row"><div><strong>Inter-house sports · 26 September</strong><span>Parents are invited. Maryam is registered with Blue House.</span></div><small>Event</small></div><div className="notice-row"><div><strong>Primary educational visit</strong><span>Guardian consent required by 18 September.</span></div><small>Action</small></div><div className="notice-row"><div><strong>Term report release</strong><span>Reports become available after section approval.</span></div><small>Academic</small></div></article>

  <article className="family-card"><header><div><h2>Parent AI</h2><p>Ask questions about your own linked children and family account.</p></div><Link href="/parent/ai">Open Parent AI →</Link></header><div className="family-callout"><strong>Try:</strong> “Why is Hafsa’s attendance lower this term?”, “What fees are still outstanding?”, or “Summarize Maryam’s latest academic report.” Parent AI cannot rank your parenting, infer private family circumstances, diagnose a child or expose staff-only notes.</div></article></section>
</main>}
