'use client';

import Link from 'next/link';
import { useState } from 'react';

export default function OnboardingPage() {
  const [step,setStep]=useState(1);
  const [school,setSchool]=useState('BrightGate Academy');
  const [campus,setCampus]=useState('Kaduna Campus');
  return <main className="onboard-shell"><section className="onboard-top"><Link className="auth-brand" href="/login"><span>S</span><strong>SchoolOS <b>AI</b></strong></Link><small>CREATE SCHOOL WORKSPACE</small></section><section className="onboard-card"><div className="onboard-head"><div><span>Step {step} of 3</span><h1>{step===1?'Tell us about your school':step===2?'Create the owner account':'Your workspace is ready'}</h1><p>{step===1?'We will use this to create your private SchoolOS tenant.':step===2?'The first account becomes the School Owner / Proprietor.':'You can now enter SchoolOS and invite your team.'}</p></div><Link href="/login">Exit</Link></div><div className="steps">{[1,2,3].map((n)=><div key={n} className={n<=step?'done':''}><i>{n<step?'✓':n}</i><span>{['School','Owner','Ready'][n-1]}</span></div>)}</div>{step===1&&<div className="onboard-form"><label>School name<input value={school} onChange={e=>setSchool(e.target.value)}/></label><label>Main campus<input value={campus} onChange={e=>setCampus(e.target.value)}/></label><label>School type<select><option>Nursery, Primary & Secondary</option><option>Primary School</option><option>Secondary School</option><option>College</option></select></label><label>Estimated active students<select><option>1–250</option><option>251–500</option><option>501–1,000</option><option>1,000+</option></select></label></div>}{step===2&&<div className="onboard-form"><label>Owner full name<input defaultValue="Ibrahim Bashir Yahaya"/></label><label>Email address<input defaultValue="owner@brightgate.edu.ng"/></label><label>Phone number<input defaultValue="+234"/></label><label>Create password<input type="password" defaultValue="password123"/></label></div>}{step===3&&<div className="ready-box"><div>✓</div><h2>{school}</h2><p>{campus}</p><ul><li>✓ Private tenant workspace created</li><li>✓ Owner role assigned</li><li>✓ Pricing set to ₦500 per active student / term</li><li>✓ Ready for staff and student onboarding</li></ul></div>}<div className="onboard-actions">{step>1&&<button className="ghost-btn" onClick={()=>setStep(step-1)}>← Back</button>}{step<3?<button className="primary-btn" onClick={()=>setStep(step+1)}>Continue →</button>:<Link className="auth-submit inline" href="/">Open school workspace →</Link>}</div></section></main>;
}
