"use client";
import Link from "next/link";
import { useState } from "react";

const docs=[
 ["Maryam Abdullahi","Term 1 Report Card","Academic report","Ready"],
 ["Hafsa Abdullahi","Primary Learning Report","Learning report","Ready"],
 ["Family Account","September Payment Receipt","Finance","Ready"],
 ["Maryam Abdullahi","Excursion Consent Form","Consent","Action needed"],
];

export default function ParentDocumentsPage(){const [consent,setConsent]=useState(false);return <main className="family-page"><header className="family-head"><div><span className="family-kicker">FAMILY ACCOUNT · DOCUMENTS</span><h1>Documents & Consent</h1><p>Family-visible reports, receipts, forms and consent records for your linked children.</p></div><div className="family-actions"><Link href="/parent">Dashboard</Link><button className="primary">Upload family document</button></div></header><section className="family-card"><header><div><h2>Available documents</h2><p>Only records approved for guardian visibility appear here.</p></div></header><div className="family-table"><div className="family-table-head"><span>Child / account</span><span>Document</span><span>Type</span><span>Status</span></div>{docs.map(r=><div className="family-table-row" key={r[1]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span><em className={r[3]==="Action needed"?"watch":""}>{r[3]}</em></div>)}</div></section><section className="family-grid two"><article className="family-card"><header><div><h2>Consent request</h2><p>Excursion · Maryam Abdullahi</p></div></header><div className="consent-card"><strong>Kaduna Museum Learning Visit</strong><span>28 September 2026 · Secondary School</span><p>The school requests guardian consent for Maryam to participate in the supervised learning visit. Transport and supervision details are provided by the school.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I have reviewed the information and give consent.</label><button disabled={!consent}>{consent?"Submit consent":"Review before consenting"}</button></div></article><article className="family-card"><header><div><h2>Consent history</h2><p>Auditable family decisions.</p></div></header><div className="family-link-list"><div><strong>Inter-house sports participation</strong><span>Approved · 02 Sep 2026 · Maryam Abdullahi</span></div><div><strong>School media / gallery use</strong><span>Declined · 20 Aug 2026 · Hafsa Abdullahi</span></div><div><strong>Emergency contact confirmation</strong><span>Confirmed · 18 Aug 2026 · Family account</span></div></div></article></section><section className="family-card"><div className="family-callout">Guardian access never includes teacher private notes, confidential safeguarding records, staff performance data, other families’ documents, or internal administrative documents that have not been approved for family visibility.</div></section></main>}
