"use client";

import { useState } from "react";

const receipts=[
 {no:"BGA/RCPT/2026/004819",student:"Maryam Abdullahi",className:"JSS 2A",admission:"BGA/2023/SEC/001",amount:25000,date:"13 Sep 2026",method:"Student Term Account",ref:"TRX-260913-94821",previous:150000,newBalance:125000,status:"Confirmed"},
 {no:"BGA/RCPT/2026/004818",student:"Muhammad Kabir",className:"Primary 5",admission:"BGA/2024/PRI/014",amount:50000,date:"13 Sep 2026",method:"Student Term Account",ref:"TRX-260913-94817",previous:100000,newBalance:50000,status:"Confirmed"},
 {no:"BGA/RCPT/2026/004817",student:"Zainab Aliyu",className:"Nursery 2",admission:"BGA/2025/NUR/007",amount:15000,date:"13 Sep 2026",method:"Student Term Account",ref:"TRX-260913-94811",previous:65000,newBalance:50000,status:"Confirmed"},
];
const money=(n:number)=>`₦${n.toLocaleString("en-NG")}`;

export default function ReceiptsPage(){const [selected,setSelected]=useState(receipts[0]);return <main><header className="fo-head"><div><span>COLLECTION RECORDS · RECEIPTS</span><h1>Receipts Register</h1><p>Every confirmed term-account credit creates a traceable receipt for Finance and the linked parent.</p></div><div className="fo-actions"><button>Export register</button><button className="primary" onClick={()=>window.print()}>Print selected</button></div></header>
<section className="fo-grid two"><article className="fo-card"><header><div><h2>Recent receipts</h2><p>Confirmed collections posted to student ledgers.</p></div></header><div className="receipt-list">{receipts.map(r=><button key={r.no} className={selected.no===r.no?"active":""} onClick={()=>setSelected(r)}><div><strong>{r.student}</strong><span>{r.className} · {r.date}</span></div><b>{money(r.amount)}</b><small>{r.no}</small></button>)}</div></article>
<article className="fo-card printable-receipt"><div className="receipt-brand"><div><span>S</span><div><strong>BrightGate Academy</strong><small>Kaduna Campus · Knowledge · Character · Excellence</small></div></div><em>PAYMENT RECEIPT</em></div><div className="receipt-number"><span>Receipt No.</span><strong>{selected.no}</strong><small>{selected.status}</small></div><div className="receipt-detail-grid"><div><span>Student</span><strong>{selected.student}</strong></div><div><span>Admission No.</span><strong>{selected.admission}</strong></div><div><span>Class</span><strong>{selected.className}</strong></div><div><span>Term</span><strong>2026/2027 · Term 1</strong></div><div><span>Amount paid</span><strong>{money(selected.amount)}</strong></div><div><span>Payment method</span><strong>{selected.method}</strong></div><div><span>Transaction ref</span><strong>{selected.ref}</strong></div><div><span>Payment date</span><strong>{selected.date}</strong></div></div><div className="receipt-balance"><div><span>Previous balance</span><strong>{money(selected.previous)}</strong></div><div><span>Payment received</span><strong>- {money(selected.amount)}</strong></div><div><span>New balance</span><strong>{money(selected.newBalance)}</strong></div></div><div className="receipt-footer">System-generated SchoolOS prototype receipt · linked automatically to the student fee ledger.</div></article></section></main>}
