"use client";
import {useState} from "react";

const seed=[
 {ref:"BNK-260913-881",sender:"A. Abdullahi",amount:"₦50,000",channel:"Bank transfer",match:"Maryam Abdullahi",status:"Matched"},
 {ref:"BNK-260913-879",sender:"Unknown sender",amount:"₦80,000",channel:"Bank transfer",match:"Unmatched",status:"Review"},
 {ref:"MON-260913-412",sender:"Hajiya Aisha Musa",amount:"₦25,000",channel:"Monthly debit",match:"Fatima Musa",status:"Matched"},
 {ref:"BNK-260913-865",sender:"Sani Ibrahim",amount:"₦20,000",channel:"Term account",match:"Ibrahim Sani",status:"Matched"},
];
export default function ReconciliationPage(){const [rows,setRows]=useState(seed);function resolve(ref:string){setRows(r=>r.map(x=>x.ref===ref?{...x,match:"Manual review allocated",status:"Matched"}:x))}return <main><header className="fo-head"><div><span>FINANCE OFFICE · BANK CONTROL</span><h1>Payment Reconciliation</h1><p>Match incoming transfers and payment events to the correct student/family account with an auditable review trail.</p></div><div className="fo-actions"><button className="primary">Import bank statement</button></div></header><section className="fo-kpis"><article><span>Today received</span><strong>₦1.24m</strong><small>38 payment events</small></article><article><span>Auto-matched</span><strong>31</strong><small>Term accounts / references</small></article><article><span>Unmatched</span><strong>7</strong><small>₦386,000</small></article><article><span>Reversals</span><strong>3</strong><small>Awaiting evidence</small></article><article><span>Match rate</span><strong>81.6%</strong><small>Today</small></article></section><section className="fo-card"><header><div><h2>Reconciliation queue</h2><p>Never allocate an ambiguous transfer solely from name similarity.</p></div></header><div className="fo-table"><div className="fo-table-head"><span>Reference</span><span>Sender</span><span>Channel</span><span>Match</span><span>Status</span></div>{rows.map(r=><div className="fo-table-row" key={r.ref}><div><strong>{r.ref}</strong><small>{r.amount}</small></div><span>{r.sender}</span><span>{r.channel}</span><span>{r.match}</span>{r.status==="Review"?<button onClick={()=>resolve(r.ref)}>Review & match</button>:<em>{r.status}</em>}</div>)}</div></section><section className="fo-grid equal" style={{marginTop:14}}><article className="fo-card"><header><div><h2>Matching signals</h2></div></header><div className="fo-list"><div><strong>Dedicated term account</strong><span>Strongest deterministic match.</span></div><div><strong>Payment reference</strong><span>Exact verified reference supports allocation.</span></div><div><strong>Sender name alone</strong><span>Insufficient when ambiguous; requires human review.</span></div></div></article><article className="fo-card"><header><div><h2>Reversal control</h2></div></header><div className="fo-callout">Refunds and reversals should preserve the original transaction, reason, evidence, approver, timestamp and resulting balance. Do not silently edit ledger history.</div></article></section></main>}
