import Link from "next/link";

const campuses=[
 {name:"Kaduna Campus",status:"Active",students:648,staff:64,attendance:92,fees:94,academic:81,leader:"Whole-school leadership team"},
 {name:"Zaria Campus",status:"Planned",students:0,staff:0,attendance:0,fees:0,academic:0,leader:"Not appointed"},
];

export default function ProprietorCampusesPage(){return <main className="owner-module-page">
<header className="owner-module-head"><div><span>PROPRIETOR · CAMPUS / BRANCH OVERSIGHT</span><h1>Campus Comparison</h1><p>Compare branches, capacity, finance and operating readiness without mixing campus-level authority.</p></div><div className="owner-module-actions"><Link href="/proprietor">Executive Overview</Link><Link className="primary" href="/proprietor/structure">Manage Structure</Link></div></header>
<OwnerNav active="campuses"/>
<section className="owner-module-kpis"><article><span>Active campuses</span><strong>1</strong><small>Kaduna operational</small></article><article><span>Planned campuses</span><strong>1</strong><small>Zaria concept</small></article><article><span>Total enrollment</span><strong>648</strong><small>Active-campus total</small></article><article><span>Staff</span><strong>64</strong><small>Teaching staff sample</small></article><article><span>Expansion readiness</span><strong>Planning</strong><small>Not yet approved</small></article></section>
<section className="owner-module-grid equal">{campuses.map(c=><article className="owner-campus-card" key={c.name}><span>{c.status.toUpperCase()} CAMPUS</span><h3>{c.name}</h3><p>{c.status==="Active"?"Current full school operation with Nursery, Primary and Secondary.":"Future branch placeholder. No students, staff or finance should be counted until formally activated."}</p><div className="owner-campus-metrics"><div><span>Students</span><strong>{c.students}</strong></div><div><span>Staff</span><strong>{c.staff}</strong></div><div><span>Attendance</span><strong>{c.status==="Active"?`${c.attendance}%`:"—"}</strong></div><div><span>Fees</span><strong>{c.status==="Active"?`${c.fees}%`:"—"}</strong></div></div><div className="owner-module-callout" style={{marginTop:10}}>{c.status==="Active"?`Leadership: ${c.leader}. Academic indicator ${c.academic}%.`:"Before activation: define campus leadership, sections, fee policy, staffing, transport, safety and operating calendar."}</div></article>)}</section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>Expansion checklist</h2><p>Owner controls before a new campus is marked active.</p></div></header><div className="owner-module-list"><div><strong>Governance & leadership</strong><span>Campus head, section leaders and delegated authority defined.</span></div><div><strong>Capacity & staffing</strong><span>Classrooms, teachers, support staff and timetable readiness reviewed.</span></div><div><strong>Finance configuration</strong><span>Fee structure, accounts, collection channels and reporting scope configured.</span></div><div><strong>Safety & operations</strong><span>Transport, visitor controls, health, safeguarding and emergency procedures configured.</span></div></div></article><article className="owner-module-card"><header><div><h2>Campus isolation principle</h2><p>Multi-campus must not mean unrestricted access.</p></div></header><div className="owner-module-callout warn">A staff member appointed to Kaduna Campus should not automatically see or manage Zaria Campus. In production, campus scope must be enforced before records reach the user or AI context.</div></article></section>
</main>}
function OwnerNav({active}:{active:string}){const links=[["finance","Finance","/proprietor/finance"],["enrollment","Enrollment","/proprietor/enrollment"],["staff","Staff & HR","/proprietor/staff"],["reports","Reports","/proprietor/reports"],["campuses","Campuses","/proprietor/campuses"],["ai","Proprietor AI","/proprietor/ai"]];return <nav className="owner-module-nav">{links.map(([k,l,h])=><Link key={k} className={active===k?"active":""} href={h}>{l}</Link>)}</nav>}