import Link from "next/link";

const leaders=[
 ["Mrs. Maryam Abdullahi","Head Teacher","Nursery / Early Years","12 staff","On track"],
 ["Mrs. Hauwa Sule","Headmistress","Primary School","28 staff","On track"],
 ["Mr. Ibrahim Danladi","Principal","Secondary School","24 staff","Review"],
 ["Mrs. Zainab Musa","Vice Principal Academics","Secondary School","Academic leadership","On track"],
];

export default function ProprietorStaffPage(){return <main className="owner-module-page">
<header className="owner-module-head"><div><span>PROPRIETOR · PEOPLE & HR</span><h1>Staff & HR Overview</h1><p>Whole-school staffing, leadership, attendance, workload and employment-risk oversight without exposing unnecessary payroll detail.</p></div><div className="owner-module-actions"><Link href="/proprietor">Executive Overview</Link><Link className="primary" href="/proprietor/structure">Manage Leadership</Link></div></header>
<OwnerNav active="staff"/>
<section className="owner-module-kpis"><article><span>Teaching staff</span><strong>64</strong><small>Across three sections</small></article><article><span>Staff attendance</span><strong>96%</strong><small>Current prototype average</small></article><article><span>Heavy workload</span><strong>5</strong><small>Review before new assignments</small></article><article><span>Open vacancies</span><strong>2</strong><small>Primary class teacher + lab support</small></article><article><span>Contracts due</span><strong>7</strong><small>Within next 60 days</small></article></section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>Leadership & staffing overview</h2><p>Section ownership and current staffing context.</p></div></header><div className="owner-module-table"><div className="owner-module-table-head"><span>Leader</span><span>Role</span><span>Scope</span><span>Team</span><span>Signal</span></div>{leaders.map(r=><div className="owner-module-row" key={r[0]}><div><strong>{r[0]}</strong><small>{r[1]}</small></div><span>{r[1]}</span><span>{r[2]}</span><b>{r[3]}</b><em className={r[4]==="Review"?"watch":""}>{r[4]}</em></div>)}</div></article><article className="owner-module-card"><header><div><h2>People attention queue</h2><p>Owner-level issues, not day-to-day supervision.</p></div></header><div className="owner-module-list"><div><strong>Primary 6 class-teacher gap</strong><span>Assign a confirmed class teacher before the next planning cycle.</span><small>Owner: Headmistress</small></div><div><strong>Five staff with heavy workload</strong><span>Review assignments before adding periods or administrative duties.</span><small>Owner: Section leaders</small></div><div><strong>Seven contracts approaching renewal</strong><span>HR review should consider role need, documented performance context and policy—not an automatic score.</span><small>Owner: HR / Proprietor</small></div></div></article></section>
<section className="owner-module-grid equal"><article className="owner-module-card"><header><div><h2>Staff mix</h2><p>Current teaching-staff distribution.</p></div></header><div className="owner-module-summary"><div><span>Early Years</span><strong>12</strong><small>Educators + assistants</small></div><div><span>Primary</span><strong>28</strong><small>Class + specialists</small></div><div><span>Secondary</span><strong>24</strong><small>Subject teachers</small></div></div></article><article className="owner-module-card"><header><div><h2>HR privacy boundary</h2><p>Leadership overview is not payroll access.</p></div></header><div className="owner-module-callout warn">The proprietor may have authority to grant HR/finance access, but ordinary leadership views should not automatically expose staff bank details, salary deductions, loan balances or private medical information. Those remain need-to-know.</div></article></section>
</main>}
function OwnerNav({active}:{active:string}){const links=[["finance","Finance","/proprietor/finance"],["enrollment","Enrollment","/proprietor/enrollment"],["staff","Staff & HR","/proprietor/staff"],["reports","Reports","/proprietor/reports"],["campuses","Campuses","/proprietor/campuses"],["ai","Proprietor AI","/proprietor/ai"]];return <nav className="owner-module-nav">{links.map(([k,l,h])=><Link key={k} className={active===k?"active":""} href={h}>{l}</Link>)}</nav>}