"use client";
import Link from "next/link";
import { useState } from "react";

const threads=[
 {id:"M1",name:"Mrs. Amina Yusuf",role:"Class Teacher · JSS 2A",child:"Maryam Abdullahi",preview:"Maryam completed the Mathematics assessment well today.",time:"16:20",unread:true},
 {id:"M2",name:"Mrs. Khadija Musa",role:"Class Teacher · Primary 3",child:"Hafsa Abdullahi",preview:"Please continue the short reading practice at home this week.",time:"Yesterday",unread:false},
 {id:"M3",name:"School Finance Office",role:"Finance",child:"Family account",preview:"Your September payment receipt is available.",time:"12 Sep",unread:false},
];

export default function ParentMessagesPage(){const [selected,setSelected]=useState(threads[0]);const [draft,setDraft]=useState("");const [sent,setSent]=useState(false);return <main className="family-page"><header className="family-head"><div><span className="family-kicker">FAMILY ACCOUNT · COMMUNICATION</span><h1>Messages</h1><p>Contact teachers and approved school offices about your linked children without exposing staff private channels.</p></div><div className="family-actions"><Link href="/parent">Dashboard</Link><button className="primary">New message</button></div></header><section className="family-message-layout"><aside className="family-card message-list"><header><div><h2>Conversations</h2><p>School-managed family communication.</p></div></header>{threads.map(t=><button key={t.id} className={selected.id===t.id?"selected":""} onClick={()=>{setSelected(t);setSent(false)}}><div><strong>{t.name}</strong><small>{t.role}</small><span>{t.child}</span><p>{t.preview}</p></div><time>{t.time}</time>{t.unread&&<i/>}</button>)}</aside><article className="family-card message-thread"><header><div><h2>{selected.name}</h2><p>{selected.role} · {selected.child}</p></div></header><div className="family-chat"><div className="school"><small>{selected.name}</small><p>{selected.preview}</p><time>{selected.time}</time></div><div className="guardian"><small>You</small><p>Thank you. I have seen this update and will follow up at home.</p><time>16:34</time></div></div><div className="message-compose"><textarea value={draft} onChange={e=>{setDraft(e.target.value);setSent(false)}} placeholder="Write a message to the school..."/><div><span>{sent?"Prototype message sent locally.":"Messages are visible only to authorized participants."}</span><button onClick={()=>{if(draft.trim()){setDraft("");setSent(true)}}}>Send message</button></div></div></article></section><section className="family-card" style={{marginTop:14}}><div className="family-callout">Use SchoolOS messaging for guardian–school communication. Teachers do not need to expose private phone numbers, and a guardian cannot access internal staff notes or conversations about other families.</div></section></main>}
