import Link from "next/link";

const reports=[
 ["Executive Term Review","Finance · enrollment · attendance · academic · operations","Updated today","Ready"],
 ["Finance Collection Report","Billing · collections · outstanding · financing","Updated 17:20","Ready"],
 ["Enrollment & Retention Report","Applications · conversion · active enrollment · retention","Updated today","Ready"],
 ["Staff & Leadership Report","Staffing · attendance · workload · leadership context","Updated today","Ready"],
 ["School Life & Operations Report","Activities · transport · events · incidents · visitors","Updated today","Ready"],
];

export default function ProprietorReportsPage(){return <main className="owner-module-page">
<header className="owner-module-head"><div><span>PROPRIETOR · EXECUTIVE REPORTING</span><h1>Executive Reports</h1><p>Board-ready summaries and owner-level evidence across finance, enrollment, people, academics and operations.</p></div><div className="owner-module-actions"><Link href="/proprietor">Executive Overview</Link><button className="primary">Create report pack</button></div></header>
<OwnerNav active="reports"/>
<section className="owner-module-kpis"><article><span>Report packs</span><strong>12</strong><small>Current session</small></article><article><span>Scheduled</span><strong>4</strong><small>Weekly / monthly / term</small></article><article><span>Owner KPIs</span><strong>18</strong><small>Across major functions</small></article><article><span>Open exceptions</span><strong>4</strong><small>Need context before closure</small></article><article><span>Last executive pack</span><strong>12 Sep</strong><small>Current prototype date</small></article></section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>Available reports</h2><p>Designed for decision review rather than raw operational data dumps.</p></div></header><div className="owner-module-table"><div className="owner-module-table-head"><span>Report</span><span>Coverage</span><span>Updated</span><span>Status</span><span>Action</span></div>{reports.map(r=><div className="owner-module-row" key={r[0]}><div><strong>{r[0]}</strong><small>{r[1]}</small></div><span>{r[1]}</span><span>{r[2]}</span><em>{r[3]}</em><b>Open</b></div>)}</div></article><article className="owner-module-card"><header><div><h2>Board / owner pack</h2><p>Suggested contents for a formal monthly review.</p></div></header><div className="owner-module-list"><div><strong>1. Executive summary</strong><span>Top changes, risks, decisions and follow-up owners.</span></div><div><strong>2. Finance & enrollment</strong><span>Collections, arrears, enrollment movement and retention.</span></div><div><strong>3. Academic & attendance</strong><span>Section trends with context, not a single opaque score.</span></div><div><strong>4. People & operations</strong><span>Staffing, workload, transport, School Life and major incidents.</span></div></div></article></section>
<section className="owner-module-grid equal"><article className="owner-module-card"><header><div><h2>Report cadence</h2><p>Prototype scheduling concept.</p></div></header><div className="owner-module-summary"><div><span>Weekly</span><strong>Operations</strong><small>Exceptions + owner queue</small></div><div><span>Monthly</span><strong>Executive</strong><small>Finance + people + enrollment</small></div><div><span>Termly</span><strong>Board</strong><small>Full-school review</small></div></div></article><article className="owner-module-card"><header><div><h2>Reporting principle</h2><p>Evidence first.</p></div></header><div className="owner-module-callout">Reports should preserve the source context behind indicators, distinguish missing data from poor performance, and clearly label mock/estimated values. AI may summarize evidence, but should not fabricate causes or silently turn operational metrics into employment or student judgments.</div></article></section>
</main>}
function OwnerNav({active}:{active:string}){const links=[["finance","Finance","/proprietor/finance"],["enrollment","Enrollment","/proprietor/enrollment"],["staff","Staff & HR","/proprietor/staff"],["reports","Reports","/proprietor/reports"],["campuses","Campuses","/proprietor/campuses"],["ai","Proprietor AI","/proprietor/ai"]];return <nav className="owner-module-nav">{links.map(([k,l,h])=><Link key={k} className={active===k?"active":""} href={h}>{l}</Link>)}</nav>}