import Link from "next/link";

const accounts=[
 ["STU-001","Maryam Abdullahi","JSS 2A","1047263815","₦185,000","₦135,000","₦50,000"],
 ["STU-002","Ibrahim Sani","JSS 2A","1047263823","₦185,000","₦85,000","₦100,000"],
 ["STU-003","Yusuf Bello","JSS 2B","1047263831","₦185,000","₦65,000","₦120,000"],
 ["PRI-003","Hafsa Abdullahi","Primary 3","1047263914","₦145,000","₦95,000","₦50,000"],
];
export default function AccountsPage(){return <main><header className="fo-head"><div><span>FINANCE OFFICE · STUDENT ACCOUNTS</span><h1>Student & Family Accounts</h1><p>Billing, term payment accounts, balances and payment-plan context for enrolled students.</p></div><div className="fo-actions"><Link className="primary" href="/finance">Open detailed Finance Center</Link></div></header><section className="fo-kpis"><article><span>Active student accounts</span><strong>648</strong><small>Across all sections</small></article><article><span>Term billed</span><strong>₦62.8m</strong><small>Current term</small></article><article><span>Collected</span><strong>₦59.1m</strong><small>94.1%</small></article><article><span>Open balances</span><strong>73</strong><small>Family accounts</small></article><article><span>Payment plans</span><strong>118</strong><small>Guardian-authorized</small></article></section><section className="fo-card"><header><div><h2>Account register</h2><p>Sample operational accounts. Use the detailed Finance Center for account-level actions.</p></div></header><div className="fo-table"><div className="fo-table-head"><span>ID / Student</span><span>Class</span><span>Term account</span><span>Billed / paid</span><span>Balance</span></div>{accounts.map(r=><div className="fo-table-row" key={r[0]}><div><strong>{r[1]}</strong><small>{r[0]}</small></div><span>{r[2]}</span><code>{r[3]}</code><span>{r[4]} / {r[5]}</span><b>{r[6]}</b></div>)}</div></section><section className="fo-card" style={{marginTop:14}}><div className="fo-callout">Finance staff may manage billing and payment records, but fee balances must not alter academic grades, awards, classroom treatment or student-risk scoring.</div></section></main>}
