import Link from "next/link";

const rows=[
  ["Nursery / Early Years","₦8.4m","₦8.1m","96%","Healthy"],
  ["Primary School","₦27.6m","₦25.1m","91%","Healthy"],
  ["Secondary School","₦26.8m","₦25.9m","86%","Watch"],
];

export default function ProprietorFinancePage(){return <main className="owner-module-page">
<header className="owner-module-head"><div><span>PROPRIETOR · FINANCE OVERSIGHT</span><h1>Owner Finance</h1><p>Executive visibility into collections, outstanding balances, family payment plans and education financing exposure.</p></div><div className="owner-module-actions"><Link href="/proprietor">Executive Overview</Link><Link className="primary" href="/finance">Open Finance Center</Link></div></header>
<OwnerNav active="finance"/>
<section className="owner-module-kpis"><article><span>Term billed</span><strong>₦62.8m</strong><small>All active student accounts</small></article><article><span>Collected</span><strong>₦59.1m</strong><small>94.1% collection rate</small></article><article><span>Outstanding</span><strong>₦3.7m</strong><small>73 family accounts</small></article><article><span>Auto-pay plans</span><strong>118</strong><small>Parent-authorized monthly plans</small></article><article><span>Education financing</span><strong>₦150k</strong><small>Outstanding financed balance</small></article></section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>Collection by section</h2><p>Owner-level comparison without exposing unnecessary family detail.</p></div></header><div className="owner-module-table"><div className="owner-module-table-head"><span>Section</span><span>Billed</span><span>Collected</span><span>Rate</span><span>Status</span></div>{rows.map(r=><div className="owner-module-row" key={r[0]}><strong>{r[0]}</strong><b>{r[1]}</b><b>{r[2]}</b><b>{r[3]}</b><em className={r[4]==="Watch"?"watch":""}>{r[4]}</em></div>)}</div></article><article className="owner-module-card"><header><div><h2>Owner attention</h2><p>Financial items requiring oversight.</p></div></header><div className="owner-module-list"><div><strong>Secondary collection below target</strong><span>86% collected against 92% owner target.</span><small>Finance + Principal follow-up</small></div><div><strong>73 family balances remain open</strong><span>Payment plans and financing should be reviewed separately from academic treatment.</span><small>No child penalty automation</small></div><div><strong>118 monthly auto-pay mandates</strong><span>Parent-controlled schedules remain opt-in and revocable according to policy.</span><small>Consent required</small></div></div></article></section>
<section className="owner-module-grid equal"><article className="owner-module-card"><header><div><h2>Collection trend</h2><p>Seven-week current-term progression.</p></div></header><div className="owner-module-bars">{[72,78,81,84,88,91,94].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><b>{v}%</b><span>W{i+1}</span></div>)}</div></article><article className="owner-module-card"><header><div><h2>Finance governance</h2><p>What the proprietor should see and control.</p></div></header><div className="owner-module-callout">Owner finance should show aggregate cash collection, exposure, exceptions, approved financing and policy-level controls. Detailed parent banking data, debit credentials and sensitive repayment notes remain restricted to authorized finance roles.</div></article></section>
</main>}

function OwnerNav({active}:{active:string}){const links=[["finance","Finance","/proprietor/finance"],["enrollment","Enrollment","/proprietor/enrollment"],["staff","Staff & HR","/proprietor/staff"],["reports","Reports","/proprietor/reports"],["campuses","Campuses","/proprietor/campuses"],["ai","Proprietor AI","/proprietor/ai"]];return <nav className="owner-module-nav">{links.map(([k,l,h])=><Link key={k} className={active===k?"active":""} href={h}>{l}</Link>)}</nav>}