import Link from "next/link";

const sectionRows=[
  ["Nursery / Early Years","₦9.87m","₦0.42m","₦9.45m","₦8.91m","94%"],
  ["Primary School","₦41.47m","₦2.36m","₦39.11m","₦32.95m","84%"],
  ["Secondary School","₦51.43m","₦4.62m","₦46.81m","₦39.74m","85%"],
];

const aging=[
  ["0–30 days","₦8.2m","Current / newly due"],
  ["31–60 days","₦5.4m","Follow-up window"],
  ["61–90 days","₦3.1m","Structured review"],
  ["90+ days","₦2.0m","Priority owner visibility"],
];

export default function ProprietorFinancePage(){return <main className="owner-module-page">
<header className="owner-module-head"><div><span>PROPRIETOR · REVENUE ASSURANCE</span><h1>School Finance & Revenue Assurance</h1><p>See what the school billed, what was reduced by scholarships and discounts, what has been collected, what remains overdue, what the store is selling, and what the school is spending.</p></div><div className="owner-module-actions"><Link href="/proprietor">Executive Overview</Link><Link href="/finance-office/collections">Smart Collections</Link><Link href="/proprietor/finance/approvals">Concession Approvals</Link><Link className="primary" href="/finance-office">Open Finance Office</Link></div></header>
<OwnerNav active="finance"/>
<section className="owner-module-kpis"><article><span>Gross term fees</span><strong>₦102.77m</strong><small>Before concessions</small></article><article><span>Scholarships & discounts</span><strong>₦7.40m</strong><small>Approved reductions</small></article><article><span>Net collectible</span><strong>₦95.37m</strong><small>Actual parent/sponsor obligation</small></article><article><span>Collected</span><strong>₦81.60m</strong><small>85.6% of net collectible</small></article><article><span>Open receivables</span><strong>₦13.77m</strong><small>Before future mandate attempts</small></article></section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>Revenue bridge</h2><p>How gross school fees become real collectible revenue.</p></div></header><div className="owner-module-list"><div><strong>Gross billed · ₦102.77m</strong><span>Nursery, Primary and Secondary standard fees plus enrolled services.</span><small>Starting billing base</small></div><div><strong>Less scholarships & discounts · ₦7.40m</strong><span>Founder awards, academic support, sibling discounts and staff-child benefits.</span><small>Not debt</small></div><div><strong>Net collectible · ₦95.37m</strong><span>The amount families and sponsors are actually expected to pay.</span><small>Collection ceiling base</small></div><div><strong>Collected · ₦81.60m</strong><span>Confirmed bank/API collections and other reconciled payments.</span><small>Receipts issued automatically in the UI model</small></div></div></article><article className="owner-module-card"><header><div><h2>Owner attention</h2><p>Exceptions that materially affect cash collection.</p></div></header><div className="owner-module-list"><div><strong>₦6.8m backed by active mandates</strong><span>Authorized future deductions already have a collection path.</span><small>Monitor success/failure rate</small></div><div><strong>₦7.3m has no active arrangement</strong><span>These balances need finance follow-up, payment plans or owner-approved action.</span><small>Highest collection priority</small></div><div><strong>11 failed mandate attempts</strong><span>Retry, reschedule or contact guardians rather than treating them as ordinary unpaid promises.</span><small>Finance action queue</small></div><div><strong>2 over-limit attempts</strong><span>Student term accounts blocked unusually large payments until Finance authorizes a higher collection ceiling.</span><small>Control working as designed</small></div></div></article></section>
<section className="owner-module-card"><header><div><h2>Collection by school section</h2><p>Gross charges, concessions, net collectible and realized collections.</p></div></header><div className="owner-module-table"><div className="owner-module-table-head"><span>Section</span><span>Gross fees</span><span>Concessions</span><span>Net collectible</span><span>Collected</span><span>Rate</span></div>{sectionRows.map(r=><div className="owner-module-row" key={r[0]}><strong>{r[0]}</strong><b>{r[1]}</b><b>{r[2]}</b><b>{r[3]}</b><b>{r[4]}</b><em className={r[5]==="84%"?"watch":""}>{r[5]}</em></div>)}</div></section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>Outstanding fee aging</h2><p>How long open receivables have remained unpaid after approved concessions.</p></div></header><div className="owner-module-list">{aging.map(r=><div key={r[0]}><strong>{r[0]} · {r[1]}</strong><span>{r[2]}</span><small>See Finance Office aging queue for arrangement-level detail</small></div>)}</div></article><article className="owner-module-card"><header><div><h2>Collection arrangements</h2><p>Outstanding does not always mean unplanned debt.</p></div></header><div className="owner-module-list"><div><strong>Active bank/salary mandates · ₦6.8m</strong><span>Consent-backed scheduled deductions.</span><small>412 active mandates</small></div><div><strong>Manual payment plans · ₦3.4m</strong><span>Families paying agreed amounts over time.</span><small>Partial deposits supported</small></div><div><strong>Education financing · ₦1.2m</strong><span>Structured financed school-fee obligations.</span><small>Separate repayment ledger</small></div><div><strong>No arrangement · ₦7.3m</strong><span>Requires collection follow-up.</span><small>Owner attention</small></div></div></article></section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>School Store revenue</h2><p>Books, uniforms and other sundry sales are tracked separately from tuition.</p></div></header><div className="owner-module-list"><div><strong>Books · ₦4.8m</strong><span>Order-linked store payments only.</span><small>Separate store receipts</small></div><div><strong>Uniforms · ₦3.2m</strong><span>Linked to inventory issue records.</span><small>Stock movement monitored</small></div><div><strong>Sportswear & other items · ₦1.1m</strong><span>Dynamic order accounts with exact payment ceilings.</span><small>No school-fee balance impact</small></div><div><strong>Total store revenue · ₦9.1m</strong><span>Reported outside tuition collections.</span><small><Link href="/finance-office/store">Open School Store →</Link></small></div></div></article><article className="owner-module-card"><header><div><h2>Store control</h2><p>Payment confirmation must reconcile with physical issue of goods.</p></div></header><div className="owner-module-list"><div><strong>486 orders issued</strong><span>Books, uniforms and other school-store requests.</span><small>Current-term sample</small></div><div><strong>419 paid</strong><span>Payments reconciled through order-specific accounts.</span><small>Separate from tuition</small></div><div><strong>9 paid but not issued</strong><span>Money received, goods still pending collection/fulfillment.</span><small>Priority proprietor exception</small></div><div><strong>7 partially issued</strong><span>Some items supplied while others remain pending.</span><small>Inventory follow-up required</small></div></div></article></section>
<section className="owner-module-grid equal"><article className="owner-module-card"><header><div><h2>Term collection trend</h2><p>Net collectible realized by week.</p></div></header><div className="owner-module-bars">{[32,45,57,66,74,80,86].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><b>{v}%</b><span>W{i+1}</span></div>)}</div></article><article className="owner-module-card"><header><div><h2>Expense & cash watch</h2><p>Proprietor-level operating context.</p></div></header><div className="owner-module-list"><div><strong>Operating expenses · ₦52.8m</strong><span>Utilities, transport, feeding, materials, maintenance and administration.</span><small>Current-term sample</small></div><div><strong>Payroll · ₦21.8m</strong><span>Processed through restricted payroll workflow.</span><small>Finance sees payment batch, not unrelated HR records</small></div><div><strong>Expected next 30 days · ₦11.3m</strong><span>Mandates, payment plans and scheduled family commitments.</span><small>Forecast, not guaranteed cash</small></div></div></article></section>
<section className="owner-module-grid equal"><article className="owner-module-card"><header><div><h2>Owner quick access</h2><p>Go directly to the finance control point that needs attention.</p></div></header><div className="owner-module-list"><div><strong>Fee Structure</strong><span>Review Nursery, Primary and Secondary billing rules.</span><small><Link href="/finance-office/fee-structure">Open fee structure →</Link></small></div><div><strong>Scholarships & Discounts</strong><span>See how much support reduces parent obligations.</span><small><Link href="/finance-office/scholarships">Open concessions →</Link> · <Link href="/proprietor/finance/approvals">Approve requests →</Link></small></div><div><strong>School Store</strong><span>Review orders, dynamic accounts, inventory and paid-but-not-issued exceptions.</span><small><Link href="/finance-office/store">Open store →</Link></small></div><div><strong>Outstanding & Aging</strong><span>Separate scheduled collections from genuinely unarranged debt.</span><small><Link href="/finance-office/debt-aging">Open aging →</Link></small></div></div></article><article className="owner-module-card"><header><div><h2>Finance governance</h2><p>Owner visibility without exposing unnecessary banking secrets.</p></div></header><div className="owner-module-callout">The proprietor should see school-wide revenue, store sales, concessions, receivables, mandate performance, expenses and exceptions. Debit credentials, sensitive bank authorization data and private repayment notes stay restricted to authorized finance workflows.</div></article></section>
</main>}

function OwnerNav({active}:{active:string}){const links=[["finance","Finance","/proprietor/finance"],["enrollment","Enrollment","/proprietor/enrollment"],["staff","Staff & HR","/proprietor/staff"],["reports","Reports","/proprietor/reports"],["campuses","Campuses","/proprietor/campuses"],["ai","Proprietor AI","/proprietor/ai"]];return <nav className="owner-module-nav">{links.map(([k,l,h])=><Link key={k} className={active===k?"active":""} href={h}>{l}</Link>)}</nav>}
