"use client";
import Link from "next/link";
import { useState } from "react";

const ledger=[
 ["13 Sep 2026","Maryam Abdullahi","TRX-260913-94821","Student Term Account","₦25,000","Confirmed"],
 ["12 Sep 2026","Hafsa Abdullahi","TRX-260912-0041","Student Term Account","₦20,000","Confirmed"],
 ["06 Sep 2026","Maryam Abdullahi","TRX-260906-0033","Student Term Account","₦20,000","Confirmed"],
 ["28 Aug 2026","Maryam Abdullahi","TRX-260828-0008","Payment mandate","₦15,000","Confirmed"],
];

const children=[
 {name:"Maryam Abdullahi",className:"JSS 2A",account:"1047263815",bank:"Partner Bank A",gross:"₦185,000",adjustment:"₦0",paid:"₦60,000",balance:"₦125,000"},
 {name:"Hafsa Abdullahi",className:"Primary 3",account:"1047263914",bank:"Partner Bank A",gross:"₦145,000",adjustment:"₦10,000 sibling discount",paid:"₦80,000",balance:"₦55,000"},
];

export default function ParentFinancePage(){
 const [autoPay,setAutoPay]=useState(true);const [debitDay,setDebitDay]=useState("25th");const [amount,setAmount]=useState("30000");const [copied,setCopied]=useState("");
 async function copyAccount(account:string){try{await navigator.clipboard.writeText(account);setCopied(account);}catch{setCopied(account)}}
 return <main className="family-page"><header className="family-head"><div><span className="family-kicker">FAMILY ACCOUNT · SMART COLLECTIONS</span><h1>Finance & Payments</h1><p>Pay each child through a unique term account, make small deposits anytime, view balances and print confirmed receipts.</p></div><div className="family-actions"><Link href="/parent">Dashboard</Link><Link href="/parent/finance/receipts">View receipts</Link></div></header>
 <section className="family-finance-kpis"><article><span>Gross term fees</span><strong>₦330,000</strong><small>Two linked children</small></article><article><span>Discounts</span><strong>₦10,000</strong><small>Sibling discount</small></article><article><span>Paid</span><strong>₦140,000</strong><small>Across both term accounts</small></article><article><span>Outstanding</span><strong>₦180,000</strong><small>Net family obligation</small></article></section>
 <section className="family-grid two"><article className="family-card"><header><div><h2>Student term accounts</h2><p>Each account is unique to the child and remains fixed for the active term.</p></div></header><div className="family-account-list">{children.map(child=><div key={child.account}><div><strong>{child.name}</strong><span>{child.className} · 2026/2027 Term 1</span></div><div><small>{child.bank}</small><b>{child.account}</b><button className="family-save" style={{marginTop:6}} onClick={()=>copyAccount(child.account)}>{copied===child.account?"Copied":"Copy account"}</button></div><div><small>Outstanding</small><b>{child.balance}</b><span>{child.adjustment}</span></div></div>)}</div><div className="family-callout" style={{marginTop:10}}>You can deposit smaller amounts at any time. Each confirmed credit reduces the child’s school-fee balance automatically. Large payments above the authorized collection limit require a special arrangement with the school Finance Office.</div></article>
 <article className="family-card"><header><div><h2>Automatic payment mandate</h2><p>Optional recurring collection connected to the same school-fee ledger.</p></div></header><div className="family-plan"><label><span>Automatic monthly charge</span><button className={autoPay?"toggle on":"toggle"} onClick={()=>setAutoPay(v=>!v)}><i/></button></label><label><span>Monthly amount</span><input value={amount} onChange={e=>setAmount(e.target.value)}/></label><label><span>Preferred debit day</span><select value={debitDay} onChange={e=>setDebitDay(e.target.value)}><option>5th</option><option>10th</option><option>15th</option><option>20th</option><option>25th</option><option>28th</option></select></label><label><span>Collection method</span><select defaultValue="bank"><option value="bank">Bank direct debit · prototype</option><option value="salary">Salary-linked collection · prototype</option></select></label><button className="family-save">Save payment mandate preference</button><div className="family-callout">Prototype UI only. This represents a parent-authorized mandate and does not create any real debit instruction.</div></div></article></section>
 <section className="family-card"><header><div><h2>Payment history</h2><p>Every confirmed credit is linked to the child and creates a receipt.</p></div><Link href="/parent/finance/receipts">Open receipt center</Link></header><div className="family-table"><div className="family-table-head"><span>Date</span><span>Child</span><span>Reference</span><span>Channel</span><span>Amount</span><span>Status</span></div>{ledger.map(r=><div className="family-table-row" key={r[2]}>{r.map((v,i)=>i===5?<em key={i}>{v}</em>:i===4?<b key={i}>{v}</b>:<span key={i}>{v}</span>)}</div>)}</div></section>
 <section className="family-grid two"><article className="family-card"><header><div><h2>How the account works</h2><p>Simple payment experience for the family.</p></div></header><div className="family-list"><div><strong>1. Transfer any affordable amount</strong><span>Use the child’s term account number.</span></div><div><strong>2. SchoolOS identifies the child</strong><span>The account maps directly to that child and active term.</span></div><div><strong>3. Balance updates</strong><span>Confirmed credit reduces the outstanding school-fee obligation.</span></div><div><strong>4. Receipt becomes available</strong><span>View, print or save from the Parent Portal.</span></div></div></article><article className="family-card"><header><div><h2>Finance principle</h2><p>Payment history is a factual record—not a child score.</p></div></header><div className="family-callout">SchoolOS must not use family payment history to lower grades, restrict classroom support, rank families, or automatically approve/deny future financing.</div></article></section></main>}
