import Link from "next/link";

const pipeline=[
 ["Nursery / Early Years",31,24,18,84,"96%"],
 ["Primary School",46,35,29,286,"97%"],
 ["Secondary School",54,41,32,278,"95%"],
];

export default function ProprietorEnrollmentPage(){return <main className="owner-module-page">
<header className="owner-module-head"><div><span>PROPRIETOR · ENROLLMENT & ADMISSIONS</span><h1>Enrollment & Admissions</h1><p>Owner-level visibility into demand, admissions conversion, retention and section capacity.</p></div><div className="owner-module-actions"><Link href="/proprietor">Executive Overview</Link><button className="primary">Export enrollment brief</button></div></header>
<OwnerNav active="enrollment"/>
<section className="owner-module-kpis"><article><span>Active students</span><strong>648</strong><small>+29 net this session</small></article><article><span>New applications</span><strong>131</strong><small>Current admission cycle</small></article><article><span>Offers issued</span><strong>100</strong><small>76% of applications</small></article><article><span>Accepted</span><strong>79</strong><small>79% offer conversion</small></article><article><span>Retention</span><strong>96%</strong><small>Whole-school current estimate</small></article></section>
<section className="owner-module-grid two"><article className="owner-module-card"><header><div><h2>Admissions pipeline by section</h2><p>Demand and conversion across the school.</p></div></header><div className="owner-module-table"><div className="owner-module-table-head"><span>Section</span><span>Applications</span><span>Offers</span><span>Accepted</span><span>Retention</span></div>{pipeline.map(r=><div className="owner-module-row" key={String(r[0])}><strong>{r[0]}</strong><b>{r[1]}</b><b>{r[2]}</b><b>{r[3]}</b><em>{r[5]}</em></div>)}</div></article><article className="owner-module-card"><header><div><h2>Capacity watch</h2><p>Where owner decisions may be needed.</p></div></header><div className="owner-module-list"><div><strong>Primary is nearing configured capacity</strong><span>286 active pupils against a mock planning capacity of 320.</span><small>Consider classroom and staffing readiness before expansion</small></div><div><strong>Secondary demand is strongest</strong><span>54 applications in the current mock intake cycle.</span><small>Review science-lab and teacher capacity before accepting additional places</small></div><div><strong>Early Years retention remains healthy</strong><span>96% retention with 84 active children.</span><small>Family engagement remains a major retention driver</small></div></div></article></section>
<section className="owner-module-grid equal"><article className="owner-module-card"><header><div><h2>Enrollment trend</h2><p>Seven checkpoints across the current planning window.</p></div></header><div className="owner-module-bars">{[598,612,621,630,638,644,648].map((v,i)=><div key={v}><i style={{height:`${Math.max(18,(v-570)*1.4)}px`}}/><b>{v}</b><span>P{i+1}</span></div>)}</div></article><article className="owner-module-card"><header><div><h2>Enrollment governance</h2><p>Owner policy boundary.</p></div></header><div className="owner-module-callout">Admissions should support eligibility, capacity and documented school policy. SchoolOS should not make opaque admissions decisions from family income, ethnicity, religion, disability, health history or other sensitive traits.</div></article></section>
</main>}
function OwnerNav({active}:{active:string}){const links=[["finance","Finance","/proprietor/finance"],["enrollment","Enrollment","/proprietor/enrollment"],["staff","Staff & HR","/proprietor/staff"],["reports","Reports","/proprietor/reports"],["campuses","Campuses","/proprietor/campuses"],["ai","Proprietor AI","/proprietor/ai"]];return <nav className="owner-module-nav">{links.map(([k,l,h])=><Link key={k} className={active===k?"active":""} href={h}>{l}</Link>)}</nav>}