"use client";

import Link from "next/link";
import { useState } from "react";

export default function WebsiteManagerPage(){
 const [hero,setHero]=useState("A strong beginning. A confident future.");
 const [admissionsOpen,setAdmissionsOpen]=useState(true);
 const [notice,setNotice]=useState("");
 return <main className="admin-page">
  <header className="admin-page-head"><div><span>ADMINISTRATION · SCHOOL WEBSITE</span><h1>Website Manager</h1><p>Manage the public-facing BrightGate Academy website while SchoolOS remains invisible to parents and visitors.</p></div><div className="admin-head-actions"><Link href="/admissions">Preview website</Link><button className="primary" onClick={()=>setNotice("Website changes saved locally in this UI prototype.")}>Save changes</button></div></header>
  <section className="admin-kpis"><article><span>Domain</span><strong style={{fontSize:14}}>brightgateacademy.ng</strong><small>Branded school website</small></article><article><span>Admissions</span><strong>{admissionsOpen?"Open":"Closed"}</strong><small>2026/2027 intake</small></article><article><span>Applications</span><strong>131</strong><small>From website</small></article><article><span>Published notices</span><strong>8</strong><small>Public website content</small></article><article><span>Last update</span><strong style={{fontSize:14}}>Today</strong><small>Prototype content state</small></article></section>
  {notice&&<section className="admin-callout"><strong>Saved</strong><p>{notice}</p></section>}
  <section className="admin-grid two"><article className="admin-card"><header><div><h2>Homepage</h2><p>Control the main public message and admission status.</p></div></header><div className="admin-form-grid"><label>Hero headline<input value={hero} onChange={e=>setHero(e.target.value)}/></label><label>Hero supporting text<textarea rows={4} defaultValue="Nursery, Primary and Secondary education in a caring, structured learning environment."/></label><label>Admissions status<select value={admissionsOpen?"open":"closed"} onChange={e=>setAdmissionsOpen(e.target.value==="open")}><option value="open">Admissions open</option><option value="closed">Admissions closed</option></select></label><label>Admission session<select defaultValue="2026"><option value="2026">2026/2027</option><option value="2027">2027/2028</option></select></label></div></article>
   <article className="admin-card"><header><div><h2>Public website sections</h2><p>Choose what the school publishes publicly.</p></div></header><div className="admin-list"><div><strong>About the school</strong><span>Mission, values, leadership and school story.</span><small>Published</small></div><div><strong>Admissions</strong><span>Admission process, requirements and online application.</span><small>Published</small></div><div><strong>School Life</strong><span>Activities, approved gallery content and events.</span><small>Published</small></div><div><strong>News & Notices</strong><span>Public announcements only.</span><small>Published</small></div><div><strong>Contact</strong><span>Campus address, phone, email and enquiry form.</span><small>Published</small></div></div></article></section>
  <section className="admin-grid two"><article className="admin-card"><header><div><h2>Admissions form settings</h2><p>What applicants are asked to provide online.</p></div></header><div className="admin-list"><div><strong>Child identity</strong><span>Name, date of birth, gender and proposed section/class.</span><small>Required</small></div><div><strong>Guardian details</strong><span>Name, phone, email and address.</span><small>Required</small></div><div><strong>Previous school</strong><span>Optional for younger applicants; configurable by section.</span><small>Configurable</small></div><div><strong>Documents</strong><span>Birth certificate, previous school report and guardian ID.</span><small>Required by policy</small></div></div></article><article className="admin-card"><header><div><h2>Branding & identity</h2><p>The public website belongs to the school brand.</p></div></header><div className="admin-info-grid"><div><span>Website name</span><strong>BrightGate Academy</strong></div><div><span>Domain</span><strong>brightgateacademy.ng</strong></div><div><span>Logo</span><strong>BGA mark</strong></div><div><span>Theme</span><strong>School theme variables</strong></div></div><div className="admin-callout" style={{marginTop:12}}><strong>White-label principle</strong><p>Parents, applicants and public visitors interact with BrightGate Academy. SchoolOS operates the management layer behind the school’s own brand.</p></div></article></section>
 </main>
}
