const reports=[
 ["Collection Summary","Current term","Fees billed, received, balances, collection rate"],
 ["Outstanding Accounts","Current term","Open family balances by section and age"],
 ["Bank Reconciliation","Daily / monthly","Matched, unmatched, reversed and adjusted receipts"],
 ["Income & Expense Statement","Monthly","Operational income, expense categories and net position"],
 ["Education Financing Ledger","Current / historical","Principal, repayments, outstanding and status"],
 ["Payroll Payment Register","Monthly","Approved payroll batch and payment confirmation"],
];
export default function ReportsPage(){return <main><header className="fo-head"><div><span>FINANCE OFFICE · REPORTING</span><h1>Finance Reports</h1><p>Auditable operational and management reporting for authorized finance and owner review.</p></div><div className="fo-actions"><button>Export current view</button><button className="primary">Generate report pack</button></div></header><section className="fo-kpis"><article><span>Collection rate</span><strong>94.1%</strong><small>Current term</small></article><article><span>Outstanding</span><strong>₦3.7m</strong><small>73 family accounts</small></article><article><span>Monthly expenses</span><strong>₦6.4m</strong><small>September mock</small></article><article><span>Bank exceptions</span><strong>7</strong><small>Unmatched receipts</small></article><article><span>Report pack</span><strong>6</strong><small>Core finance reports</small></article></section><section className="fo-grid two"><article className="fo-card"><header><div><h2>Report library</h2><p>Core finance outputs available to the Finance Office.</p></div></header><div className="fo-list">{reports.map(r=><div key={r[0]}><strong>{r[0]}</strong><span>{r[2]}</span><small>{r[1]}</small></div>)}</div></article><aside className="fo-card"><header><div><h2>Management snapshot</h2><p>Current term.</p></div></header><div className="fo-list"><div><strong>Nursery / Early Years</strong><span>96% fee collection</span><small>Healthy</small></div><div><strong>Primary School</strong><span>91% fee collection</span><small>Healthy</small></div><div><strong>Secondary School</strong><span>86% fee collection</span><small>Watch</small></div></div><div className="fo-callout" style={{marginTop:12}}>Reports should expose the minimum necessary detail. Owner-level summaries do not need parent bank credentials or unrelated family data.</div></aside></section></main>}
